#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Собирает russian_keys.json из english_keys.json, подставляя русские переводы
из встроенного словаря. Без внешних библиотек. Запуск: python build_russian_keys.py
"""

import json
import os
import sys

if __name__ == "__main__":
    sys.stdout.reconfigure(encoding="utf-8")
    sys.stderr.reconfigure(encoding="utf-8")

# Словарь: английская строка -> живой русский перевод (игровой, не машинный)
RU = {
    # --- Addresses / Локации ---
    "203": "203",
    "204": "204",
    "205": "205",
    "110 Chinatown": "Чайнатаун, 110",
    "16 Whisper Court": "Двор Шёпота, 16",
    "1F7B Victory Square": "Победа, кв. 1F7B",
    "21 Science Square": "Научный квартал, 21",
    "42 West Whisper Lane": "Западный Шёпот, 42",
    "601 Youth Apartment": "Молодёжные апартаменты, 601",
    "616 Whisper Lane": "Улица Шёпота, 616",
    "Alchemy Lab": "Алхимическая лаборатория",
    "Epoch Stone Hall": "Зал эпох",
    "Balcony": "Балкон",
    "Meteor Bar": "Бар «Метеорит»",
    "Basement": "Подвал",
    "Bathroom": "Ванная",
    "Seaside Cabin": "Прибрежная хижина",
    "Bedroom": "Спальня",
    "BestTime Appliances": "Бытовая техника «Лучшее время»",
    "Biology Side Gallery": "Биологическая галерея",
    "Boba's Bedroom": "Спальня Бобы",
    "Brilliant Stars Jewelry Store": "Ювелирный «Яркие звёзды»",
    "Bus Stop": "Автобусная остановка",
    "Captain's Quarters": "Каюта капитана",
    "Centrol Control Room": "Центр управления",
    "Cheryl's Bakery": "Пекарня Шерил",
    "Home Theater": "Домашний кинотеатр",
    "No. 8 Convenience Store": "Минимаркет «Восьмёрка»",
    "Cream Apartment": "Кремовые апартаменты",
    "Duplex Apartment": "Двухуровневая квартира",
    "East Suburb Graveyard": "Восточное кладбище",
    "Showroom": "Шоурум",
    "Exm Residence": "Резиденция Эксм",
    "Genesis Terminal": "Терминал «Генезис»",
    "Flower Garden": "Цветочный сад",
    "Flower Shop": "Цветочный магазин",
    "Foyer": "Прихожая",
    "Baking Room": "Пекарня",
    "Garden": "Сад",
    "Grandpa's Home": "Дом дедушки",
    "Grandpa's Room": "Комната дедушки",
    "Graveyard": "Кладбище",
    "Hallway": "Коридор",
    "Herbs Lab": "Лаборатория трав",
    "Main Hall": "Главный зал",
    "Ideal Home Showroom": "Шоурум «Идеальный дом»",
    "IKA Furniture": "Мебель IKA",
    "Jewelry Shop": "Ювелирный магазин",
    "Kitchen": "Кухня",
    "Kumamoto Figurine House": "Дом фигурок Кумамото",
    "Living Room": "Гостиная",
    "Lobby": "Холл",
    "Loft Living Room": "Гостиная в лофте",
    "Luna's Duplex Apartment": "Дуплекс Луны",
    "Mahjong Table": "Стол для маджонга",
    "Mr. Tree's Furniture Store": "Мебельный «Мистер Дерево»",
    "My Home": "Мой дом",
    "Newspaper Office": "Редакция газеты",
    "Newsstand": "Газетный киоск",
    "No. 8 Convenience Store Pro": "Минимаркет «Восьмёрка» Плюс",
    "Notice Board": "Доска объявлений",
    "Parkside Underground Tunnel": "Подземный переход у парка",
    "Potion Room": "Комната зелий",
    "Random Room": "Случайная комната",
    "Red Forest Cemetery": "Кладбище Красного леса",
    "Room 205, St Vladimir Hospital": "Палата 205, больница Св. Владимира",
    "Secret Anime Figure Room": "Тайная комната аниме-фигурок",
    "Secret Base": "Тайная база",
    "Secret Chamber": "Тайная комната",
    "Self-Service Gardening Shop": "Садовый магазин самообслуживания",
    "Shasha Carpet": "Ковёр «Шаша»",
    "Shopping Mall": "Торговый центр",
    "Star Relic Hall": "Зал звёздных реликвий",
    "Studio": "Студия",
    "Subspace": "Подпространство",
    "Tasty Diner": "Кафе «Вкусно»",
    "The Bridge": "Мостик",
    "VERY PUNK Instrument Store": "Магазин инструментов «Очень панк»",
    "Tianca's Bedroom": "Спальня Тяньцы",
    "Tiancai's Cabin": "Хижина Тяньцая",
    "Tower – 1st Floor": "Башня — 1-й этаж",
    "Tower – 2nd Floor": "Башня — 2-й этаж",
    "Tower – 3rd Floor": "Башня — 3-й этаж",
    "Tower – Rooftop": "Башня — крыша",
    "Town": "Город",
    "Underground Lab": "Подземная лаборатория",
    "Villa": "Вилла",
    "Wandering General Store": "Странствующий ларек",
    "Work Area": "Рабочая зона",
    "Workshop": "Мастерская",
    "GD Real Estate": "Недвижимость GD",
    "Chill Home": "Дом «Прохлада»",
    "Hermit's Apartment": "Квартира отшельника",
    "Evergreen House": "Дом «Вечнозелёный»",
    "Park": "Парк",
    "Residential Area (Home)": "Жилой район (дом)",
    "Police Station": "Полицейский участок",
    "Basketball Court": "Баскетбольная площадка",
    "Cinema": "Кинотеатр",
    "Museum": "Музей",
    "Gas Station": "АЗС",
    "": "",
    # --- Items (начало) ---
    " Freeze-Dried Chicken": " Сублимированная курица",
    " Plush Rug": " Плюшевый коврик",
    '"Blood and DNA of Organisms"': "«Кровь и ДНК организмов»",
    '"Daily Whisper"': "«Ежедневный шёпот»",
    '"Diary of the Starfolk"': "«Дневник звёздного народа»",
    '"Great Museum Events Through the Years"': "«Великие события музея за годы»",
    '"Museum Management I"': "«Управление музеем I»",
    '"Museum Management II"': "«Управление музеем II»",
    '"Ocean Whisper" Perfume': "Парфюм «Шёпот океана»",
    '"Origin of Species" Display Panel': "Панель «Происхождение видов»",
    '"Paleontological Studies"': "«Палеонтологические исследования»",
    "《Fountain》": "«Фонтан»",
    "10×10 Display Stand": "Стойка 10×10",
    "100 Everyday Pastries Illustrated": "100 видов выпечки в картинках",
    "100,000 Whys": "Сто тысяч почему",
    "1250 Single Mattress": "Односпальный матрас 1250",
    "1x1 Furniture Display Stand": "Стойка 1x1",
    "4×7 Display Stand": "Стойка 4×7",
    "4k Projection Screen": "4K проекционный экран",
    "4x2 Product Basket": "Корзина 4x2",
    "4x4 Product Basket": "Корзина 4x4",
    "52-Inch Big TV": "Телевизор 52 дюйма",
    "8×6 Display Stand": "Стойка 8×6",
    "8×8 Display Stand": "Стойка 8×8",
    "A bundle of rope": "Моток верёвки",
    "A Corpse Under The Fireworks": "Труп под фейерверком",
    "A History Of Capitalism": "История капитализма",
    "A Large Pipe": "Большая труба",
    "A Page of Notes": "Листок с заметками",
    "A Plate of Cake": "Тарелка с пирожным",
    "Abandoned Bed": "Заброшенная кровать",
    "Academic Book Set": "Набор учебников",
    "Acid Nutrient Fluid": "Кислотный питательный раствор",
    "Ad Board": "Рекламный щит",
    "Adjustment Device": "Регулировочное устройство",
    "Advanced Food Packing Box": "Продвинутая упаковка для еды",
    "African Violet": "Сенполия",
    "African Violet Growth Stage": "Сенполия (рост)",
    "African Violet Seed": "Семена сенполии",
    "Agatha": "Агата",
    "Age Brewed Vinegar": "Выдержанный уксус",
    "Aged Copper Metal Bucket": "Медное ведро со следами времени",
    "Aged Wine": "Выдержанное вино",
    "Agent Rules and Daily Schedule": "Правила агента и распорядок дня",
    "AIEE Happy Fizz": "Весёлая шипучка AIEE",
    "AIFA Happy Fizz": "Весёлая шипучка AIFA",
    "AIFA Happy Fizz (Empty)": "Весёлая шипучка AIFA (пустая)",
    "AIHF Happy Fizz": "Весёлая шипучка AIHF",
    "AIHF Happy Fizz (Empty)": "Весёлая шипучка AIHF (пустая)",
    "Air Conditioner": "Кондиционер",
    "Air Wall 1": "Воздушная стена 1",
    "Air Yordan Basketball Shoes": "Баскетбольные кроссовки Air Yordan",
    "Air Yordan Sneakers": "Кроссовки Air Yordan",
    "AJ3": "AJ3",
    "Alchemical Small Energy Orb (Negative)": "Алхимический сгусток энергии (отрицательный)",
    "Alchemist Kitchen Window (Large)": "Окно кухни алхимика (большое)",
    "Alchemist Kitchen Window (Medium)": "Окно кухни алхимика (среднее)",
    "Alchemist Kitchen Window (Small)": "Окно кухни алхимика (малое)",
    "Alchemist Switch (Default Off)": "Выключатель алхимика (выкл.)",
    "Alchemist's Alchemy Room to Herb Room": "Из алхимической в травяную",
    "Alchemist's Alchemy Room to Kitchen": "Из алхимической на кухню",
    "Alchemist's Bathroom Wall and Floor 1": "Стена и пол ванной алхимика 1",
    "Alchemist's Herb Room Wall & Floor 10": "Стена и пол травяной 10",
    "Alchemist's Kitchen to Bathroom": "Из кухни в ванную",
    "Alchemist's Lab Notes": "Записки алхимика",
    "Alchemist's Living Room Empty Object 1": "Пустой объект гостиной алхимика 1",
    "Alchemist's Living Room Empty Object 2": "Пустой объект гостиной алхимика 2",
    "Alchemist's Living Room Wall & Floor 19": "Стена и пол гостиной 19",
    "Alchemist's Mirror World Wall 1": "Стена зеркального мира 1",
    "Alchemist's Mirror World Wall 2": "Стена зеркального мира 2",
    "Alchemist's Room to Outside": "Выход наружу",
    "Alchemist's Room to Outside – Empty Object 1": "Выход наружу — пустой объект 1",
    "Alchemist's Room to Outside – Empty Object 2": "Выход наружу — пустой объект 2",
    "Alchemist's Second Floor Railing  ": "Перила второго этажа алхимика",
    "Alchemist's Workshop Empty Object": "Пустой объект мастерской",
    "Alchemy Gift Box": "Подарочная коробка алхимика",
    "Alchemy Lab Floor Plan": "План этажа алхимической лаборатории",
    "Alchemy workshop stage text": "Текст сцены мастерской",
    "Alcohol Hand Sanitizer": "Спиртовой антисептик",
    "Alcohol Wipes": "Спиртовые салфетки",
    "Alien Flower": "Инопланетный цветок",
    "Alien flower": "Инопланетный цветок",
    "Alien Flower – Seed Stage": "Инопланетный цветок — семя",
    "Alien Nutrient Solution": "Инопланетный питательный раствор",
    "Alien Seed": "Инопланетное семя",
    "Alien Seed (Discarded)": "Инопланетное семя (выброшено)",
    "Alien Soil": "Инопланетная почва",
    "All-in-One Pet Bowl": "Универсальная миска для питомца",
    "Alpaca Storage Stool": "Пуфик-хранилище «Альпака»",
    "Alphabet Light Sign": "Световая вывеска с буквами",
    "Altar Offering Table": "Жертвенный стол алтаря",
    "Amber Flower String": "Янтарная гирлянда цветов",
    "Amethyst": "Аметист",
    "Amethyst Crystal Ball": "Хрустальный шар из аметиста",
    "Amino Acid Face Wash": "Умывалка с аминокислотами",
    "Amp Cabinet": "Усилитель (кабинет)",
    "Amp Head": "Головка усилителя",
    "Ancestor Ore": "Руда предков",
    "Ancient Ape Sculpture": "Древняя скульптура обезьяны",
    "Ancient Bird Fossil": "Ископаемая древняя птица",
    "Ancient Blue-Winged Dragonfly": "Древняя стрекоза с синими крыльями",
    "Ancient Civilizations and Their Herbal Wisdom": "Древние цивилизации и травничество",
    "Ancient Cockpit Steering Wheel": "Древний штурвал кабины",
    "Ancient Dinosaur Fossil": "Ископаемый динозавр",
    "Ancient Display Stand": "Древняя витрина",
    "Ancient Dragonfly": "Древняя стрекоза",
    "Ancient Dragonfly Fossil": "Ископаемая стрекоза",
    "Ancient Fan-Leaf Plant Fossil": "Ископаемое вееролистное растение",
    "Ancient Fern": "Древний папоротник",
    "Ancient Fern Fossil": "Ископаемый папоротник",
    "Ancient Green-Winged Dragonfly": "Древняя стрекоза с зелёными крыльями",
    "Ancient Insect Fossil": "Ископаемое насекомое",
    "Ancient Jellyfish Fossil": "Ископаемая медуза",
    "Ancient Jetpack": "Древний реактивный ранец",
    "Ancient Lamprey Fossil": "Ископаемая минога",
    "Ancient Red-Winged Dragonfly": "Древняя стрекоза с красными крыльями",
    "Ancient Sapling": "Древний саженец",
    "Ancient Scroll I": "Древний свиток I",
    "Ancient Scroll II": "Древний свиток II",
    "Ancient Sea Anemone Fossil": "Ископаемая актиния",
    "Ancient Star": "Древняя звезда",
    "Ancient Starfish Fossil": "Ископаемая морская звезда",
    "Ancient Sword": "Древний меч",
    "Ancient Telephone": "Древний телефон",
    "Ancient Tree": "Древнее дерево",
    "Ancient Vine": "Древняя лоза",
    "Ancient Vine Sapling": "Саженец древней лозы",
    "And Then There Were None": "И не осталось никого",
    "Angel Cat Carpet": "Коврик «Ангельский кот»",
    "Anime Poster": "Аниме-постер",
    "Anna": "Анна",
    "Anna's Gift Box": "Подарочная коробка Анны",
    "Anthurium": "Антуриум",
    "Anthurium Seed": "Семена антуриума",
    "Anti-Theft Display Floor Tile 1": "Напольная витрина 1",
    "Anti-Theft Display Floor Tile 2": "Напольная витрина 2",
    "Anti-Theft Display Floor Tile 3": "Напольная витрина 3",
    "Anti-Theft Display Floor Tile 4": "Напольная витрина 4",
    "Anti-Theft Glass Display 1": "Стеклянная витрина 1",
    "Anti-Theft Glass Display 2": "Стеклянная витрина 2",
    "Anti-Theft Glass Display 3": "Стеклянная витрина 3",
    "Anti-Theft Glass Display 4": "Стеклянная витрина 4",
    "Antique Bronze Coffee Machine": "Старинная бронзовая кофемашина",
    "Antique Bronze Water Cup": "Старинная бронзовая кружка",
    "Antique Slate Pattern Rug": "Коврик под сланец",
    "Antique-Style Wooden Lattice Screen": "Деревянная решётка в старинном стиле",
    "Antler Moth": "Бархатница",
    "Apartment Floor": "Пол квартиры",
    "Apartment Wall 1": "Стена квартиры 1",
    "Apartment Wall 2": "Стена квартиры 2",
    "Ape Sculpture": "Скульптура обезьяны",
    "Apple": "Яблоко",
    "Apple Cider": "Яблочный сидр",
    "Apple Green Dress": "Платье яблочно-зелёное",
    "Apple Green Plastic Bath Brush": "Яблочно-зелёная мочалка",
    "Apple Green Plastic Slippers": "Тапочки яблочно-зелёные",
    "Apple Green Towel": "Полотенце яблочно-зелёное",
    "Arched Floor-to-Ceiling Window": "Арочное окно в пол",
    "Arched Gravestone (Damaged)": "Арочное надгробие (повреждено)",
    "Asparagus Cochinchinensis": "Спаржа кохинхинская",
    "Asparagus Fern": "Аспарагус",
    "Astrolabe": "Астролябия",
    "Astronaut Model": "Модель космонавта",
    "Astronomical Telescope": "Астрономический телескоп",
    "Automatic Feeder": "Автокормушка",
    "Avocado Bean Bag Chair": "Кресло-мешок авокадо",
    "Avocado Green Dining Table": "Обеденный стол авокадо",
    "Avocado Green Double Sofa Chair": "Двухместный диван авокадо",
    "Avocado Green Long-Staple Cotton Towel": "Махровое полотенце авокадо",
    "Avocado Green Tablecloth Dining Table": "Обеденный стол с скатертью авокадо",
    "Avocado Green Two-Seater Fabric Sofa": "Двухместный тканевый диван авокадо",
    "Avocado Green Wooden Chair": "Деревянный стул авокадо",
    "Avocado Sofa Pillow": "Диванная подушка авокадо",
    "Awl": "Шило",
    "Azuki-colored Hanging Shelf": "Полка подвесная цвета адзуки",
    "Baby Powder": "Детская присыпка",
    "Back": "Назад",
    "Back of Computer Case": "Тыльная сторона системника",
    "Back of Mouse": "Тыльная сторона мыши",
    "Back of Sofa 6": "Спинка дивана 6",
    "Back of Television": "Тыльная сторона телевизора",
    "Back Side": "Обратная сторона",
    "Bag of Almond Powder": "Пакет миндальной муки",
    "Bag of Baking Powder": "Пакет разрыхлителя",
    "Bag of Cocoa Powder": "Пакет какао",
    "Bag of Flour": "Пакет муки",
    "Bag of Milk Powder": "Пакет сухого молока",
    "Bag of Sugar": "Пакет сахара",
    "Bagua Sapling": "Саженец багуа",
    "Bagua Tree": "Дерево багуа",
    "Baked Croissant": "Испечённый круассан",
    "Baked Dorayaki": "Испечённое дораяки",
    "Baked Egg Tart": "Испечённый тарт с яйцом",
    "Baked Palmier": "Испечённое пальмер",
    "Baked Soft European Bread": "Испечённый мягкий хлеб",
    "Bakery Gift Box": "Подарочная коробка из пекарни",
    "Bakery to Exterior": "Выход из пекарни",
    "Baking Brush": "Кисть для выпечки",
    "Baking Tray": "Противень",
    "Balance Scale": "Весы",
    "Balcony Floor – Home Unit 2": "Пол балкона — блок 2",
    "Balcony Railing Left – Home Unit 2": "Перила балкона слева — блок 2",
    "Balcony Railing Left 2 – Home Unit 2": "Перила балкона слева 2 — блок 2",
    "Balcony Railing Right – Home Unit 2": "Перила балкона справа — блок 2",
    "Balcony to Bedroom – Home Unit 2": "Балкон — спальня, блок 2",
    "Balcony Wall": "Стена балкона",
    "Balcony Wall – Home Unit 2": "Стена балкона — блок 2",
    "Ball Lightning": "Шаровая молния",
    "Ball Sewn From Fabric Scraps": "Мячик из лоскутков",
    "Balloon Cat": "Кот-шарик",
    "Balloon Cat Display Board": "Витрина «Кот-шарик»",
    "Bamboo Umbrella Stand": "Подставка для зонтов из бамбука",
    "Banana": "Банан",
    "Banana Peel": "Банановая кожура",
    "Bandit King": "Король разбойников",
    "Cream White Bar Counter Table": "Барная стойка кремово-белая",
    "Bar counter with ambient light": "Барная стойка с подсветкой",
    "Bar Neon Blackboard": "Неоновая доска бара",
    "Bar Stool": "Барный табурет",
    "Barbecue Grill": "Мангал",
    "Barbie Pink Single Bed": "Односпальная кровать «Барби»",
    "Barnacle on Underground Wall 1": "Ракушки на стене 1",
    "Barnacle on Underground Wall 2": "Ракушки на стене 2",
    "Barnacle on Underground Wall 3": "Ракушки на стене 3",
    "Barnacle on Underground Wall 4": "Ракушки на стене 4",
    "Barnacle on Underground Wall 5": "Ракушки на стене 5",
    "Basement Entrance Blocked by Planks": "Вход в подвал забит досками",
    "Basement Switch": "Выключатель подвала",
    "Basic Plastic Trash Can": "Обычная пластиковая урна",
    "Basic Porcelain Toilet": "Обычный фаянсовый унитаз",
    "Basic Rubber Boots": "Обычные резиновые сапоги",
    "Basic Soap": "Обычное мыло",
    "Basic Sponge": "Обычная губка",
    "Basic White Plastic Clothes Hanger": "Обычная белая вешалка",
    "Basket Full of Flowers": "Корзина цветов",
    "Basket Full of Fruit": "Корзина фруктов",
    "Basket Full of Pinecones": "Корзина шишек",
    "Basketball Court Fence A1": "Ограда площадки A1",
    "Basketball Court Fence A5": "Ограда площадки A5",
    "Basketball Court Fence A6": "Ограда площадки A6",
    "Bass": "Бас",
    "Bass Guitar": "Бас-гитара",
    "Bath Towel": "Банное полотенце",
    "Bathroom (Complete)": "Ванная (готовая)",
    "Bathroom Divider Panel": "Разделительная панель ванной",
    "Bathroom Door": "Дверь ванной",
    "Bathroom Floor": "Пол ванной",
    "Bathroom Floor – Home Unit 2": "Пол ванной — блок 2",
    "Bathroom Miscellaneous Packing Box": "Коробка с мелочами для ванной",
    "Bathroom to Dining Room – Home Unit 2": "Ванная — столовая, блок 2",
    "Bathroom to Living Room": "Ванная — гостиная",
    "Bathroom to Ward": "Ванная — палата",
    "Bathroom Wall Left – Home Unit 2": "Стена ванной слева — блок 2",
    "Bathroom Wall Right – Home Unit 2": "Стена ванной справа — блок 2",
    "Bathtub": "Ванна",
    "Bathtub Shelf": "Полка у ванны",
    "Battle for the Inheritance": "Битва за наследство",
    "BBQ Flavored Chips (Bag)": "Чипсы со вкусом барбекю (пачка)",
    "Beach Courtyard": "Двор у пляжа",
    "Beach Parasol": "Пляжный зонт",
    "Beach Travel Postcard": "Открытка с пляжа",
    "Beach-Colored Pillow": "Подушка пляжных цветов",
    "Bean Bag Sofa": "Диван-мешок",
    "Bed 2-3": "Кровать 2-3",
    "Bedroom Floor – Home Unit 2": "Пол спальни — блок 2",
    "Bedroom to Balcony – Home Unit 2": "Спальня — балкон, блок 2",
    "Bedroom to Dining Room – Home Unit 2": "Спальня — столовая, блок 2",
    "Bedroom to Hallway": "Спальня — коридор",
    "Bedroom to Secret Room": "Спальня — тайная комната",
    "Bedroom Wall Left – Home Unit 2": "Стена спальни слева — блок 2",
    "Bedroom Wall Right – Home Unit 2": "Стена спальни справа — блок 2",
    "Bedroom Wall Right 2 – Home Unit 2": "Стена спальни справа 2 — блок 2",
    "Bedside Table 2": "Тумбочка 2",
    "Beef Jerky": "Вяленая говядина",
    "Beige 3-Seater Sofa": "Бежевый трёхместный диван",
    "Beige Apron": "Бежевый фартук",
    "Beige Mini Shelf": "Бежевая мини-полка",
    "Beige patterned long carpet": "Бежевый длинный ковёр с узором",
    "Beige Towel": "Бежевое полотенце",
    "Beige Wooden Shoe Cabinet": "Бежевый деревянный обувной шкаф",
    "Beige Wool Boots": "Бежевые войлочные сапожки",
    "Beige-Gray Ceramic Sink Storage Cabinet Bottom": "Низ тумбы под раковину бежево-серой",
    "Beige-Gray Ceramic Sink Storage Cabinet Top": "Верх тумбы под раковину бежево-серой",
    "Beige-Gray Ceramic Sink Storage Cabinet Vertical 1": "Бок тумбы под раковину 1",
    "Beige-Gray Ceramic Sink Storage Cabinet Vertical 2": "Бок тумбы под раковину 2",
    "Bento Box": "Бэнто",
    "Bergamot Perfume": "Парфюм с бергамотом",
    "Berry Pie": "Ягодный пирог",
    "Berry Pudding": "Ягодный пудинг",
    "Beverage Dispenser": "Диспенсер напитков",
    "Big Bottle of Fish Food": "Большая банка корма для рыбок",
    "Big Mouth Speaker": "Колонка «Большой рот»",
    "Big Tree": "Большое дерево",
    "Big Tree 1": "Большое дерево 1",
    "Big Tree 2": "Большое дерево 2",
    "Big Tree 3": "Большое дерево 3",
    "Bird Album": "Альбом птиц",
    "Bird's Nest Fern": "Папоротник «птичье гнездо»",
    "Birthday Banner": "Праздничный баннер",
    "Black and Gold Electric Guitar": "Электрогитара чёрно-золотая",
    "Black and Gold Guitar": "Гитара чёрно-золотая",
    "Black and Red Checkerboard Rug": "Коврик в клетку чёрно-красный",
    "Black Ceramic Rinse Cup": "Чёрная керамическая кружка для полоскания",
    "Black File Folder": "Чёрная папка",
    "Black Fishing Line": "Чёрная леска",
    "Black Fishing Rod": "Чёрная удочка",
    "Black Folding Stool": "Чёрный складной табурет",
    "Black Goji Nourishing Shampoo": "Шампунь с годжи",
    "Black Jellyfish Grass": "Чёрная медузная трава",
    "Black Lacquered Desk Lamp": "Чёрная лакированная настольная лампа",
    "Black Lacquered Retro Refrigerator": "Ретро-холодильник чёрный лакированный",
    "Black lacquered retro refrigerator": "Ретро-холодильник чёрный лакированный",
    "Black Metal Leather Chair": "Кресло чёрное металл-кожа",
    "Black Metal Storage Rack": "Чёрная металлическая стойка",
    "Black Metal Table": "Чёрный металлический стол",
    "Black Pants": "Чёрные брюки",
    "Black Plastic Stool": "Чёрный пластиковый табурет",
    "Black Plate": "Чёрная тарелка",
    "Black Shiba Figurine": "Фигурка чёрного сиба-ину",
    "Black Shiba Inu Wall Art": "Картина с чёрным сиба-ину",
    "Black Shiba Pillow": "Подушка «Чёрный сиба»",
    "Black Tea": "Чёрный чай",
    "Black Toilet Base": "Чёрная основа унитаза",
    "Black Toilet Tank": "Чёрный бачок унитаза",
    "Black Wood Wicker Chair": "Чёрное плетёное кресло",
    "Black-and-White TV": "Чёрно-белый телевизор",
    "Black-Gold Electric Guitar": "Электрогитара чёрно-золотая",
    "Blackboard": "Доска",
    "Blacktea Teacup": "Чашка для чёрного чая",
    "Blacktea Teapot": "Чайник для чёрного чая",
    "Blanket 6": "Одеяло 6",
    "Blinds": "Жалюзи",
    "Block Wall": "Блочная стена",
    "Blonde Girl Figurine": "Фигурка блондинки",
    "Blood glucose meter": "Глюкометр",
    "Blood-Pressure Relief Medication": "Препарат от давления",
    "Bloody Trash Can": "Кровавая урна",
    "Blue Abstract Painting": "Синяя абстракция",
    "Blue and White Porcelain": "Фарфор сине-белый",
    "Blue and White Porcelain Flowerpot": "Сине-белая фарфоровая ваза",
    "Blue and White Porcelain Plate": "Сине-белая фарфоровая тарелка",
    "Blue and White Porcelain Saucer": "Сине-белое блюдце",
    "Blue And White Porcelain Teacup": "Сине-белая фарфоровая чашка",
    "Blue and White Porcelain Teapot": "Сине-белый фарфоровый чайник",
    "Blue And White Stool": "Сине-белый табурет",
    "Blue And White Tank Top": "Сине-белая майка",
    "Blue Backpack": "Синий рюкзак",
    "Blue Bass": "Синий бас",
    "Blue Border Stone": "Синий бордюрный камень",
    "Blue Cell Figurine": "Фигурка синей ячейки",
    "Blue Electric Guitar": "Синяя электрогитара",
    "Blue Empty Medicine Bottle": "Синий пустой флакон лекарства",
    "Blue Enamel Mug": "Синяя эмалированная кружка",
    "Blue Fishing Line": "Синяя леска",
    "Blue Fishing Rod": "Синяя удочка",
    "Blue Flower": "Синий цветок",
    "Blue Flower Glass Jar": "Стеклянная банка с синим цветком",
    "Blue Gem Slot on Wall": "Гнездо синего камня на стене",
    "Blue Glasses Case": "Синий футляр для очков",
    "Blue Guy Figurine": "Фигурка синего парня",
    "Blue Knight Figurine": "Фигурка синего рыцаря",
    "Blue Laser Barrier": "Синий лазерный барьер",
    "Blue Long Cotton Towel": "Синее длинное махровое полотенце",
    "Blue long-staple cotton towel": "Синее махровое полотенце",
    "Blue Morpho Butterfly Specimen": "Экземпляр бабочки морфо",
    "Blue Old Bottle Cap": "Синяя старая крышка",
    "Blue Ore Tissue Box": "Синяя руда — коробка салфеток",
    "Blue Single Bed": "Синяя односпальная кровать",
    "Blue Small Tablecloth": "Синяя маленькая скатерть",
    "Blue Striped Absorbent Mat": "Синий полосатый коврик у ванны",
    "Blue Sword Samurai Figurine": "Фигурка самурая с синим мечом",
    "Blue Umbrella": "Синий зонт",
    "Blue V-Shaped Electric Guitar": "Синяя электрогитара V-образная",
    "Blue-Black Bare Metal Wall Lamp": "Стена лампа сине-чёрная металл",
    "Blue-Black Metal Camp Bed": "Раскладушка сине-чёрная металл",
    "Blue-Black Vintage Lampshade Metal Wall Lamp": "Винтажная настенная лампа сине-чёрная",
    "Blue-Gold Celebration Balloon": "Сине-золотой праздничный шарик",
    "Blue-Gray Plush Carpet": "Сине-серый плюшевый ковёр",
    "Blue-Purple Antique Butterfly": "Сине-фиолетовая старинная бабочка",
    "Blue-Purple Pillow": "Сине-фиолетовая подушка",
    "Blue-Violet Ore": "Сине-фиолетовая руда",
    "Blueberry Lychee Preserves": "Варенье из черники и личи",
    "Blueberry Plant Specimen": "Образец черники",
    "Blueberry Shampoo": "Шампунь с черникой",
    "Board": "Доска",
    "Boat 3": "Лодка 3",
    "Body lotion": "Лосьон для тела",
    "Body Wash": "Гель для душа",
    "Bomb Flower": "Цветок-бомба",
    "Bonfire": "Костёр",
    "Bookshelf Bottom Panel": "Нижняя панель книжного шкафа",
    "Bookshelf Left Panel": "Левая панель книжного шкафа",
    "Bookshelf Right Panel": "Правая панель книжного шкафа",
    "Bookshelf Top Panel": "Верхняя панель книжного шкафа",
    "Boots": "Сапоги",
    "Botanical Scented Tissue": "Салфетки с травяным ароматом",
    "Bottom": "Низ",
    "Bottom Floor": "Нижний этаж",
    "Bottom Layer": "Нижний слой",
    "Box": "Коробка",
    "Box 2": "Коробка 2",
    "Box of Weights": "Набор гирь",
    "Box Plant": "Растение в коробке",
    "Box Stool": "Табурет-коробка",
    "Boxwood Bedside Table": "Тумбочка из самшита",
    "Boxwood Bookshelf": "Книжный шкаф из самшита",
    "Boxwood Headboard": "Изголовье из самшита",
    "Boxwood Single Bed": "Односпальная кровать из самшита",
    "Braised Beef Flavored Instant Ramen": "Лапша со вкусом тушёной говядины",
    "Branch": "Ветка",
    "Branch with Pinecones": "Ветка с шишками",
    "Brandy": "Бренди",
    "Brass Bulb Floor Lamp": "Латунная торшерная лампа",
    "Brass Candle Holder": "Латунный подсвечник",
    "Brass Curved Wall Lamp": "Латунная настенная лампа",
    "Brass Elegant Candle Holder": "Латунный изящный подсвечник",
    "Brass Hollow Wall Lamp": "Латунная полая настенная лампа",
    "Brass Metal Towel Bar": "Латунная полка для полотенец",
    "Brazil Banana": "Бразильский банан",
    "Bread Basket": "Хлебная корзина",
    "Bread Pillow": "Подушка-булка",
    "Bread Waist Cushion": "Поясничная подушка-булка",
    "Breathing Light Gaming Headset": "Игровая гарнитура с подсветкой",
    "Breeze Double Window": "Двойное окно «Бриз»",
    "Brett": "Бретт",
    "Brett (After Kidnapping)": "Бретт (после похищения)",
    "Brett (After Kidnapping) 2": "Бретт (после похищения) 2",
    "Brett (After Kidnapping) 3": "Бретт (после похищения) 3",
    "Brett (After Kidnapping) 4": "Бретт (после похищения) 4",
    "Brett (Appears After All Rooms Are Done)": "Бретт (появляется после всех комнат)",
    "Brett (Appears After Ending)": "Бретт (после концовки)",
    "Brett (Appears After Museum)": "Бретт (после музея)",
    "Brett (Jewelry Shop)": "Бретт (ювелирный)",
    "Brett (Press Office)": "Бретт (редакция)",
    "Brick Phone": "Кирпичный телефон",
    "Brick Red Hardcover Book": "Книга в кирпично-красной обложке",
    "Brick Wall Partition": "Кирпичная перегородка",
    "Brick-red Hanging Shelf": "Кирпично-красная полка",
    "Bridge Travel Postcard": "Открытка с моста",
    "Bright Sitting on Chair in Thought (Luna Ending)": "Брайт в раздумьях (концовка Луны)",
    "Bright Yellow Desktop Speaker": "Ярко-жёлтая колонка",
    "Bright Yellow Hanging Rack": "Ярко-жёлтая вешалка",
    "Broccoli": "Брокколи",
    "Broccoli Produce Basket": "Корзина с брокколи",
    "Brochure": "Брошюра",
    "Broken Branch": "Сломанная ветка",
    "Broken Brick": "Сломанный кирпич",
    "Broken Bricks": "Обломки кирпичей",
    "Broken Cabinet (Furniture Store)": "Сломанный шкаф (мебельный)",
    "Broken Chair": "Сломанный стул",
    "Broken Coffee Table (Furniture Store)": "Сломанный журнальный столик (мебельный)",
    "Broken Glass 1": "Разбитое стекло 1",
    "Broken Glass 2": "Разбитое стекло 2",
    "Broken Glass 3": "Разбитое стекло 3",
    "Broken Glass 4": "Разбитое стекло 4",
    "Broken Pallet (Furniture Store)": "Сломанный поддон (мебельный)",
    "Broken Sofa (Furniture Store)": "Сломанный диван (мебельный)",
    "Broken Stone": "Разбитый камень",
    "Broken Square Table (Furniture Store)": "Сломанный квадратный стол (мебельный)",
    "Broken Stool (Furniture Store)": "Сломанный табурет (мебельный)",
    "Broken Table": "Сломанный стол",
    "Broken Table (Furniture Store)": "Сломанный стол (мебельный)",
    "Bronze Mask": "Бронзовая маска",
    "Bronze Tissue Box": "Бронзовая руда — коробка салфеток",
    "Broom": "Метла",
    "Brown File Folder": "Коричневая папка",
    "Brown Glass Reagent Bottle": "Коричневая склянка реактива",
    "Brown Vintage Double Leather Sofa": "Коричневый винтажный кожаный диван",
    "Bubble Alien Corpse 2": "Пузырчатый инопланетный труп 2",
    "Buckled Notebook": "Блокнот с пряжкой",
    "Bug Spray": "Спрей от насекомых",
    "Bullet Head Gravestone (Damaged)": "Надгробие пулевидное (повреждено)",
    "Bulletin Board": "Доска объявлений",
    "Bumper Pole": "Отбойный столб",
    "Bumper Pole 2": "Отбойный столб 2",
    "Bun Head": "Голова с пучком",
    "Bunny Backrest Leather Sofa": "Кожаный диван со спинкой-зайцем",
    "Bunny Ear Corner Railing": "Угловые перила с ушками",
    "Bunny Ear Railing": "Перила с ушками",
    "Bunny Ear Railing Corner Post": "Угловой столб перил с ушками",
    "Bunny Ear Touchscreen Temperature Control Shower": "Душ с сенсорной панелью и ушками",
    "Bunny Pillow": "Подушка-зайчик",
    "Bunny Plush": "Плюшевый зайчик",
    "Bunny Quilt": "Одеяло с зайчиками",
    "Bunny Clothing Store Owner": "Владелица магазина одежды с зайчиками",
    "Burnt Ash 1": "Пепел 1",
    "Burnt Ash 2": "Пепел 2",
    "Burnt Ash 3": "Пепел 3",
    "Burnt Croissant": "Подгоревший круассан",
    "Burnt Dorayaki": "Подгоревшее дораяки",
    "Burnt Egg Tart": "Подгоревший тарт",
    "Burnt Palmier": "Подгоревшее пальмер",
    "Burnt Soft European Bread": "Подгоревший мягкий хлеб",
    "Bus Stop Foot Panel": "Панель остановки",
    "Bus Stop Sign": "Знак остановки",
    "Bus Stop Sign (Left)": "Знак остановки (слева)",
    "Bush 1": "Куст 1",
    "Bush 2": "Куст 2",
    "Butter Coffee Maker": "Кофемашина «Масло»",
    "Butter Radio": "Радио «Масло»",
    "Butter Vacuum Cleaner": "Пылесос «Масло»",
    "Cabbage": "Капуста",
    "Cabbage Plush Toy": "Плюшевая капуста",
    "Cabinet 4": "Шкаф 4",
    "Cactus": "Кактус",
    "Cactus Ball": "Шаровый кактус",
    "Cactus Seed (Discarded)": "Семя кактуса (выброшено)",
    "Cake Lamp": "Лампа-торт",
    "Cake Menu Board": "Меню тортов",
    "Cake Mold": "Форма для торта",
    "Cake Stand": "Подставка для торта",
    "Cake Takeout Bag": "Пакет для торта с собой",
    "Cake Wrapping Paper": "Упаковочная бумага для торта",
    "Calendar": "Календарь",
    "Calla Lily": "Калла",
    "Calligraphy Brush": "Кисть для каллиграфии",
    "Camel Color Striped Rug": "Полосатый коврик верблюжьего цвета",
    "Camel Glasses Case": "Футляр для очков верблюжий",
    "Camel Tile Coffee Table": "Журнальный столик верблюжий",
    "Camellia": "Камелия",
    "Camera": "Камера",
    "Camera Maintenance": "Обслуживание камеры",
    "Camping Basket": "Походная корзина",
    "Camping Box 1": "Походный ящик 1",
    "Camping Box 2": "Походный ящик 2",
    "Camping Box 3": "Походный ящик 3",
    "Camping Box 4": "Походный ящик 4",
    "Camping Chair": "Походный стул",
    "Camping Mat": "Походный коврик",
    "Camping Table": "Походный стол",
    "Candle": "Свеча",
    "Candle 1": "Свеча 1",
    "Candle 2": "Свеча 2",
    "Candle 3": "Свеча 3",
    "Candle 4": "Свеча 4",
    "Candle 5": "Свеча 5",
    "Candle 6": "Свеча 6",
    "Candle Set": "Набор свечей",
    "Cane": "Трость",
    "Cane Shaft": "Ствол трости",
    "Canned Cat Food": "Консервы для кота",
    "Canned Coffee": "Кофе в банке",
    "Canned Dog Food": "Консервы для собаки",
    "Canned Flowers": "Цветы в банке",
    "Canned Grapes": "Виноград в банке",
    "Canned Lychees": "Личи в банке",
    "Canned Nuts": "Орехи в банке",
    "Canned Strawberries": "Клубника в банке",
    "Capri Blue File Box": "Синяя папка «Капри»",
    "Capri Blue Hunting Coat": "Охотничье пальто «Капри»",
    "Capsule Coffee": "Капсульный кофе",
    "Car of Foolishness": "Машина глупости",
    "Carbon Black Gothic Bed": "Готическая кровать угольно-чёрная",
    "Carbon Black Gothic Chair": "Готический стул угольно-чёрный",
    "Carbon Black Long-Pile Carpet": "Длинноворсовый ковёр угольно-чёрный",
    "Cardboard Bed": "Картонная кровать",
    "Cardboard Box": "Картонная коробка",
    "Cardboard Box Set": "Набор картонных коробок",
    "Cardboard Box With Cat": "Картонная коробка с котом",
    "Cardboard Set": "Набор картонных коробок",
    "Carrot Ceramic Teacup": "Керамическая чашка «Морковка»",
    "Carrot Ceramic Teapot": "Керамический чайник «Морковка»",
    "Carved Wooden Bird Handle": "Резная ручка с птицей",
    "Carved Wooden Letter Box": "Резной почтовый ящик",
    "Cash Register": "Кассовый аппарат",
    "Cash Register 1": "Кассовый аппарат 1",
    "Cash Register 2": "Кассовый аппарат 2",
    "Cashier Ad Board": "Рекламный щит кассира",
    "Cast Iron Oven": "Чугунная печь",
    "Cat": "Кот",
    "Cat Ear Sofa": "Диван с кошачьими ушками",
    "Cat Food Bowl": "Миска для кота",
    "Cat food in plastic bag": "Корм для кота в пакете",
    "Cat Grave Marker": "Надгробие кота",
    "Cat Hair Roller": "Ролик от шерсти кота",
    "Cat Hole In Garden Wall": "Кошкопрой в стене сада",
    "Cat Litter": "Наполнитель для кошачьего туалета",
    "Cat Litter Box": "Лоток для кота",
    "Cat Mask": "Маска кота",
    "Cat Paw Print": "След лапки кота",
    "Cat shampoo": "Шампунь для кота",
    "Cat Skull Fossil": "Ископаемый череп кота",
    "Cat Teasing Bell": "Колокольчик для игры с котом",
    "Cat Treats": "Лакомство для кота",
    "Cat Tree": "Дерево для кота",
    "Cat's Eye Flower": "Цветок «кошачий глаз»",
    "Catnip": "Котовник",
    "Cauliflower Mouse": "Мышь-цветная капуста",
    "CD Set": "Набор CD",
    "Ceiling Light": "Потолочный светильник",
    "Cemetery well": "Колодец на кладбище",
    "Cemetery Well": "Колодец на кладбище",
    "Center": "Центр",
    "Central Building Archive": "Архив центрального здания",
    "Ceramic Charcoal Stove": "Керамическая печь на угле",
    "Ceramic Countertop Sandalwood Combination Cabinet": "Керамическая столешница и сандаловый шкаф",
    "Ceramic Tile Desk": "Стол с керамической плиткой",
    "Ceramic Toilet": "Керамический унитаз",
    "Ceramic-Framed Window": "Окно в керамической раме",
    "Ceremonial Dagger": "Церемониальный кинжал",
    "Cereus Cactus": "Цереус",
    "Chair": "Стул",
    "Rosewood Chinese Display Shelf": "Китайская полка из палисандра",
    "Charcoal Black Canvas Backpack": "Рюкзак угольно-чёрный холст",
    "Charcoal Black Gothic Arch Screen": "Готическая арочная ширма угольно-чёрная",
    "Charcoal Black Gothic Corner Railing": "Готические угловые перила угольно-чёрные",
    "Charcoal Black Gothic Fireplace": "Готический камин угольно-чёрный",
    "Charcoal Black Gothic Railing": "Готические перила угольно-чёрные",
    "Charcoal Black Gothic Storage Rack": "Готическая стойка угольно-чёрная",
    "Charcoal Black Gothic Window": "Готическое окно угольно-чёрное",
    "Charcoal Black Mini Mouse": "Мини-мышь угольно-чёрная",
    "Charcoal Fabric Fill Light": "Тканевый рассеиватель угольно-чёрный",
    "Checkerboard Decorative Painting": "Декоративная картина в клетку",
    "Checkered picnic mat": "Клетчатый пикниковый коврик",
    "Checkout Counter": "Стойка оплаты",
    "Cheese": "Сыр",
    "Chef's Knife": "Поварской нож",
    "Cheryl": "Шерил",
    "Cheryl Archive": "Архив Шерил",
    "Cheryl's Bathroom Floor": "Пол ванной Шерил",
    "Cheryl's Bathroom To Bedroom": "Ванная Шерил — спальня",
    "Cheryl's Bathroom Wall L": "Стена ванной Шерил слева",
    "Cheryl's Bathroom Wall R": "Стена ванной Шерил справа",
    "Cheryl's Bedroom Floor": "Пол спальни Шерил",
    "Cheryl's Bedroom Floor 2": "Пол спальни Шерил 2",
    "Cheryl's Bedroom To Cake Shop": "Спальня Шерил — пекарня",
    "Cheryl's Bedroom Wall 2L": "Стена спальни Шерил 2 слева",
    "Cheryl's Bedroom Wall R": "Стена спальни Шерил справа",
}


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    input_path = os.path.join(script_dir, "english_keys.json")
    output_path = os.path.join(script_dir, "russian_keys.json")

    if not os.path.exists(input_path):
        print(f"Файл не найден: {input_path}")
        return 1

    print("Загрузка english_keys.json...", flush=True)
    with open(input_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    translated = 0
    for key, en_val in data.items():
        if en_val in RU:
            data[key] = RU[en_val]
            translated += 1

    print(f"Переведено записей: {translated} из {len(data)}", flush=True)
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"Сохранено в: {output_path}", flush=True)
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except Exception as e:
        print(f"Ошибка: {e}", file=sys.stderr, flush=True)
        import traceback
        traceback.print_exc()
        sys.exit(1)
