# -*- coding: utf-8 -*-
"""
Глоссарий для естественного перевода названий предметов (ItemName).
Фразы и слова заменяются на русские эквиваленты — не сухой машинный перевод.
"""

# Полные фразы (длинные совпадения в приоритете)
PHRASES = {
    "A Corpse Under The Fireworks": "Труп под фейерверком",
    "A History Of Capitalism": "История капитализма",
    "Adjustment Device": "Регулировочное устройство",
    "Advanced Food Packing Box": "Упаковка для продуктов",
    "Age Brewed Vinegar": "Выдержанный уксус",
    "Agent Rules and Daily Schedule": "Правила агента и распорядок дня",
    "AIEE Happy Fizz": "Весёлая шипучка AIEE",
    "AIFA Happy Fizz": "Весёлая шипучка AIFA",
    "AIFA Happy Fizz (Empty)": "Весёлая шипучка AIFA (пусто)",
    "AIHF Happy Fizz": "Весёлая шипучка AIHF",
    "AIHF Happy Fizz (Empty)": "Весёлая шипучка AIHF (пусто)",
    "Air Wall 1": "Воздушная перегородка 1",
    "Alchemical Small Energy Orb (Negative)": "Малая алхимическая сфера энергии (отриц.)",
    "Alchemist Kitchen Window (Large)": "Окно кухни алхимика (большое)",
    "Alchemist Kitchen Window (Medium)": "Окно кухни алхимика (среднее)",
    "Alchemist Kitchen Window (Small)": "Окно кухни алхимика (маленькое)",
    "Alchemist Switch (Default Off)": "Выключатель алхимика (выкл. по умолч.)",
    "Alchemist's Alchemy Room to Herb Room": "Из алхимической в травяную",
    "Alchemist's Alchemy Room to Kitchen": "Из алхимической на кухню",
    "Alchemist's Bathroom Wall and Floor 1": "Стена и пол ванной алхимика 1",
    "Alchemist's Herb Room Wall & Floor 10": "Стена и пол травяной комнаты 10",
    "Alchemist's Kitchen to Bathroom": "Из кухни алхимика в ванную",
    "Alchemist's Living Room Empty Object 1": "Пустой объект гостиной 1",
    "Alchemist's Living Room Empty Object 2": "Пустой объект гостиной 2",
    "Alchemist's Living Room Wall & Floor 19": "Стена и пол гостиной 19",
    "Alchemist's Mirror World Wall 1": "Стена зеркального мира 1",
    "Alchemist's Mirror World Wall 2": "Стена зеркального мира 2",
    "Alchemist's Room to Outside": "Из комнаты алхимика наружу",
    "Alchemist's Room to Outside – Empty Object 1": "Выход наружу – пустой объект 1",
    "Alchemist's Room to Outside – Empty Object 2": "Выход наружу – пустой объект 2",
    "Alchemist's Second Floor Railing": "Перила второго этажа",
    "Alchemist's Workshop Empty Object": "Пустой объект мастерской",
    "Alchemy Gift Box": "Подарочная коробка алхимика",
    "Alchemy Lab Floor Plan": "План этажа алхимической лаборатории",
    "Alchemy workshop stage text": "Текст сцены алхимической мастерской",
    "Alcohol Hand Sanitizer": "Спиртовой антисептик для рук",
    "Alcohol Wipes": "Спиртовые салфетки",
    "Alien flower": "Инопланетный цветок",
    "Alien Flower – Seed Stage": "Инопланетный цветок — стадия семени",
    "Alien Nutrient Solution": "Инопланетный питательный раствор",
    "Alien Seed (Discarded)": "Инопланетное семя (выброшено)",
    "Alphabet Light Sign": "Световая вывеска-алфавит",
    "Amber Flower String": "Ниточка янтарных цветов",
    "Amino Acid Face Wash": "Умывалка с аминокислотами",
    "Amp Cabinet": "Шкаф для усилителя",
    "Amp Head": "Головка усилителя",
    "Ancestor Ore": "Руда предков",
    "Ancient Ape Sculpture": "Древняя скульптура обезьяны",
    "Ancient Bird Fossil": "Древняя окаменелость птицы",
    "Ancient Blue-Winged Dragonfly": "Древняя стрекоза с синими крыльями",
    "Ancient Civilizations and Their Herbal Wisdom": "Древние цивилизации и травничество",
    "Ancient Cockpit Steering Wheel": "Древний штурвал кабины",
    "Ancient Dinosaur Fossil": "Древняя окаменелость динозавра",
    "Ancient Display Stand": "Древняя витрина",
    "Ancient Dragonfly": "Древняя стрекоза",
    "Ancient Dragonfly Fossil": "Древняя окаменелость стрекозы",
    "Ancient Fan-Leaf Plant Fossil": "Древняя окаменелость вееролистного растения",
    "Ancient Fern": "Древний папоротник",
    "Ancient Fern Fossil": "Древняя окаменелость папоротника",
    "Ancient Green-Winged Dragonfly": "Древняя стрекоза с зелёными крыльями",
    "Ancient Insect Fossil": "Древняя окаменелость насекомого",
    "Ancient Jellyfish Fossil": "Древняя окаменелость медузы",
    "Ancient Jetpack": "Древний реактивный ранец",
    "Ancient Lamprey Fossil": "Древняя окаменелость миноги",
    "Ancient Red-Winged Dragonfly": "Древняя стрекоза с красными крыльями",
    "Ancient Sapling": "Древний саженец",
    "Ancient Scroll I": "Древний свиток 1",
    "Ancient Scroll II": "Древний свиток 2",
    "Ancient Sea Anemone Fossil": "Древняя окаменелость актинии",
    "Ancient Star": "Древняя звезда",
    "Ancient Starfish Fossil": "Древняя окаменелость морской звезды",
    "Ancient Sword": "Древний меч",
    "Ancient Telephone": "Древний телефон",
    "Ancient Tree": "Древнее дерево",
    "Ancient Vine": "Древняя лоза",
    "Ancient Vine Sapling": "Саженец древней лозы",
    "And Then There Were None": "И не осталось никого",
    "Angel Cat Carpet": "Коврик «Ангел-кот»",
    "Anime Poster": "Постер в стиле аниме",
    "Anna's Gift Box": "Подарочная коробка Анны",
    "Anthurium": "Антуриум",
    "Anthurium Seed": "Семя антуриума",
    "Anti-Theft Display Floor Tile 1": "Противокражная напольная плитка 1",
    "Anti-Theft Display Floor Tile 2": "Противокражная напольная плитка 2",
    "Anti-Theft Display Floor Tile 3": "Противокражная напольная плитка 3",
    "Anti-Theft Display Floor Tile 4": "Противокражная напольная плитка 4",
    "Anti-Theft Glass Display 1": "Противокражная витрина 1",
    "Anti-Theft Glass Display 2": "Противокражная витрина 2",
    "Anti-Theft Glass Display 3": "Противокражная витрина 3",
    "Anti-Theft Glass Display 4": "Противокражная витрина 4",
    "Antique Bronze Coffee Machine": "Антикварная бронзовая кофеварка",
    "Antique Bronze Water Cup": "Антикварная бронзовая кружка",
    "Antique Slate Pattern Rug": "Коврик под сланец",
    "Antique-Style Wooden Lattice Screen": "Деревянная ширма в антикварном стиле",
    "Antler Moth": "Бабочка-рогач",
    "Apartment Floor": "Пол квартиры",
    "Apartment Wall 1": "Стена квартиры 1",
    "Apartment Wall 2": "Стена квартиры 2",
    "Ape Sculpture": "Скульптура обезьяны",
    "Apple Cider": "Яблочный сидр",
    "Apple Green Dress": "Платье цвета яблока",
    "Apple Green Plastic Bath Brush": "Яблочно-зелёная мочалка",
    "Apple Green Plastic Slippers": "Яблочно-зелёные шлёпанцы",
    "Apple Green Towel": "Полотенце цвета яблока",
    "Arched Floor-to-Ceiling Window": "Арочное окно в пол",
    "Arched Gravestone (Damaged)": "Арочное надгробие (повреждено)",
    "Asparagus Cochinchinensis": "Спаржа кохинхинская",
    "Asparagus Fern": "Спаржа-папоротник",
    "Astrolabe": "Астролябия",
    "Astronaut Model": "Модель космонавта",
    "Astronomical Telescope": "Астрономический телескоп",
    "Automatic Feeder": "Автокормушка",
    "Avocado Bean Bag Chair": "Кресло-мешок цвета авокадо",
    "Avocado Green Dining Table": "Обеденный стол цвета авокадо",
    "Avocado Green Double Sofa Chair": "Двухместный диван цвета авокадо",
    "Avocado Green Long-Staple Cotton Towel": "Длинноволокнистое полотенце цвета авокадо",
    "Avocado Green Tablecloth Dining Table": "Обеденный стол со скатертью авокадо",
    "Avocado Green Two-Seater Fabric Sofa": "Двухместный тканевый диван цвета авокадо",
    "Avocado Green Wooden Chair": "Деревянный стул цвета авокадо",
    "Avocado Sofa Pillow": "Диванная подушка цвета авокадо",
    "Awl": "Шило",
    "Azuki-colored Hanging Shelf": "Подвесная полка цвета адзуки",
    "Baby Powder": "Детская присыпка",
    "Back": "Назад",
    "Back Side": "Задняя сторона",
    "Back of Computer Case": "Задняя панель системного блока",
    "Back of Mouse": "Задняя часть мыши",
    "Back of Sofa 6": "Тыльная сторона дивана 6",
    "Back of Television": "Задняя панель телевизора",
    "Baked Soft European Bread": "Выпеченный европейский хлеб",
    "Balance Scale": "Весы",
    "Balloon Cat": "Кот-шарик",
    "Balloon Cat Display Board": "Витрина «Кот-шарик»",
    "Bandit King": "Король разбойников",
    "Barbie Pink Single Bed": "Односпальная кровать цвета Барби",
    "Bar counter with ambient light": "Барная стойка с подсветкой",
    "Bar Neon Blackboard": "Неоновая вывеска бара",
    "Bar Stool": "Барный табурет",
    "Barbecue Grill": "Мангал-гриль",
    "Barnacle on Underground Wall 1": "Моллюск на подземной стене 1",
    "Barnacle on Underground Wall 2": "Моллюск на подземной стене 2",
    "Barnacle on Underground Wall 3": "Моллюск на подземной стене 3",
    "Barnacle on Underground Wall 4": "Моллюск на подземной стене 4",
    "Barnacle on Underground Wall 5": "Моллюск на подземной стене 5",
    "Basic Plastic Trash Can": "Базовая пластиковая урна",
    "Basic Porcelain Toilet": "Базовый фарфоровый унитаз",
    "Basic Soap": "Базовое мыло",
    "Basic Sponge": "Обычная губка",
    "Basic White Plastic Clothes Hanger": "Белая пластиковая вешалка",
    "Basket Full of Flowers": "Корзина цветов",
    "Basket Full of Fruit": "Корзина фруктов",
    "Basket Full of Pinecones": "Корзина шишек",
    "Bath Towel": "Банное полотенце",
    "Bathroom": "Ванная",
    "Bathroom (Complete)": "Ванная (полная)",
    "Bathroom Divider Panel": "Разделительная панель ванной",
    "Bathroom Door": "Дверь ванной",
    "Bathroom Floor": "Пол ванной",
    "Bathroom Floor – Home Unit 2": "Пол ванной – блок 2",
    "Bathroom Miscellaneous Packing Box": "Коробка с мелочами для ванной",
    "Bathroom to Dining Room – Home Unit 2": "Из ванной в столовую — блок 2",
    "Bathroom to Living Room": "Из ванной в гостиную",
    "Bathroom to Ward": "Из ванной в палату",
    "Bathroom Wall Left – Home Unit 2": "Стена ванной левая – блок 2",
    "Bathroom Wall Right – Home Unit 2": "Стена ванной правая – блок 2",
    "Bathtub": "Ванна",
    "Bathtub Shelf": "Полка для ванной",
    "Battle for the Inheritance": "Борьба за наследство",
    "BBQ Flavored Chips (Bag)": "Чипсы со вкусом барбекю",
    "Bean Bag Sofa": "Кресло-мешок",
    "Bed 2-3": "Кровать 2-3",
    "Bedroom Floor – Home Unit 2": "Пол спальни – блок 2",
    "Bedroom to Balcony – Home Unit 2": "Из спальни на балкон — блок 2",
    "Bedroom to Dining Room – Home Unit 2": "Из спальни в столовую — блок 2",
    "Bedroom to Hallway": "Из спальни в коридор",
    "Bedroom to Secret Room": "Из спальни в тайную комнату",
    "Bedroom Wall Left – Home Unit 2": "Стена спальни левая – блок 2",
    "Bedroom Wall Right – Home Unit 2": "Стена спальни правая – блок 2",
    "Bedroom Wall Right 2 – Home Unit 2": "Стена спальни правая 2 – блок 2",
    "Beach Courtyard": "Пляжный внутренний двор",
    "Beach Parasol": "Пляжный зонт от солнца",
    "Beach Travel Postcard": "Пляжная открытка",
    "Beach-Colored Pillow": "Подушка цвета песка",
    "\"Blood and DNA of Organisms\"": "«Кровь и ДНК организмов»",
    "\"Daily Whisper\"": "«Ежедневный шёпот»",
    "\"Diary of the Starfolk\"": "«Дневник звёздного народа»",
    "\"Great Museum Events Through the Years\"": "«Великие события музея за годы»",
    "\"Museum Management I\"": "«Управление музеем I»",
    "\"Museum Management II\"": "«Управление музеем II»",
    "\"Ocean Whisper\" Perfume": "Парфюм «Океанский шёпот»",
    "\"Origin of Species\" Display Panel": "Витрина «Происхождение видов»",
    "\"Paleontological Studies\"": "«Палеонтологические исследования»",
    "100 Everyday Pastries Illustrated": "100 видов выпечки в иллюстрациях",
    "100,000 Whys": "100 000 «Почему»",
    "1x1 Furniture Display Stand": "1×1 Стойка для мебели",
    "4x2 Product Basket": "4×2 Корзина для товаров",
    "4x4 Product Basket": "4×4 Корзина для товаров",
    "52-Inch Big TV": "Большой телевизор 52 дюйма",
    "8×6 Display Stand": "8×6 Стойка для экспонатов",
    "8×8 Display Stand": "8×8 Стойка для экспонатов",
    "4k Projection Screen": "4K экран для проектора",
    "AJ3": "AJ3",
    "Altar Offering Table": "Столик для подношений",
    "Chess Table": "Шахматный стол",
    "Chicken of Wisdom": "Курица мудрости",
    "Chili Powder": "Молотый перец чили",
    "Chinese Dictionary": "Китайский словарь",
    "Chopstick Holder": "Подставка для палочек",
    "Chopsticks": "Палочки для еды",
    "Chopping Board": "Разделочная доска",
    "Chrysanthemum": "Хризантема",
    "Chrysanthemum Seeds": "Семена хризантемы",
    "Citronella Geranium": "Цитронелла и герань",
    "Classic Black Mary Janes": "Классические туфли Мэри Джейн чёрные",
    "Classic Detective Movie Poster": "Постер классического детектива",
    "Classic Gunfight Movie Poster": "Постер вестерна",
    "Classic Hero Movie Poster": "Постер фильма о герое",
    "Classic Short Thriller Collection": "Классическая коллекция коротких триллеров",
    "Classic Potato Chips": "Классические чипсы",
    "Cleaning Ball": "Шар для чистки",
    "Cleaning Box": "Коробка для чистки",
    "Cleaning Trolley": "Тележка для уборки",
    "Clothes Hanger": "Вешалка для одежды",
    "Clothesline": "Бельевая верёвка",
    "Clothing Display Stand": "Стойка для одежды",
    "Clothing Packing Box": "Коробка для одежды",
    "Cloud Carpet": "Ковёр «Облако»",
    "Cloud Storage Cabinet": "Шкаф «Облако»",
    "Cloud Mat": "Коврик «Облако»",
    "Cloud Shelf": "Полка «Облако»",
    "Coated Frying Pan": "Сковорода с антипригарным покрытием",
    "Coconut Juice": "Кокосовый сок",
    "Coffee Grounds": "Кофейная гуща",
    "Coffee-Colored Alphabet Flick Mat": "Коврик с алфавитом цвета кофе",
    "Cold Devotion": "Холодная преданность",
    "Collected Short Sci-Fi Stories": "Собрание короткой научной фантастики",
    "Combat Haystack": "Боевой сеновал",
    "Computer Case": "Системный блок",
    "Confession of a Craftsman": "Исповедь мастера",
    "Confidential File": "Конфиденциальный файл",
    "Convenience Store": "Минимаркет",
    "Conveyor Belt To The Workshop (Wall)": "Конвейер к мастерской (стена)",
    "Conveyor Instruction Panel": "Панель инструкций конвейера",
    "Cream White Bar Counter Table": "Барная стойка кремового цвета",
    "Cream White Chalk Panel Corner Cabinet": "Угловой шкаф с меловой панелью кремового цвета",
    "Divider Panel": "Разделительная панель",
    "Eight Million Ways to Die": "Восемь миллионов способов умереть",
    "Elementary Detective Club Series: The Golden Mask": "Клуб юных детективов: Золотая маска",
    "Elementary Detective Club Series: The Magic Thief": "Клуб юных детективов: Волшебный вор",
    "Elementary Detective Club Series: The Magician": "Клуб юных детективов: Фокусник",
    "Elementary Detective Club Series: The Man In Black": "Клуб юных детективов: Человек в чёрном",
    "Elementary Detective Club Series: The Strange Doctor": "Клуб юных детективов: Странный доктор",
    "Grid Panel": "Сетчатая панель",
    "High School Math, Physics, and Chemistry": "Средняя школа: математика, физика и химия",
    "History of the Mediterranean Empire": "История Средиземноморской империи",
    "History Review 1": "Обзор истории 1",
    "History Review 2": "Обзор истории 2",
    "History Review 3": "Обзор истории 3",
    "History Review 4": "Обзор истории 4",
    "History Review 5": "Обзор истории 5",
    "History Review 6": "Обзор истории 6",
    "History Review 7": "Обзор истории 7",
    "History Review 8": "Обзор истории 8",
    "Ivory Metal Panel Desk": "Письменный стол с металлической панелью слоновой кости",
    "Left Ore Wall Panel 1": "Левая рудная настенная панель 1",
    "Left Ore Wall Panel 2": "Левая рудная настенная панель 2",
    "Left Ore Wall Panel 3": "Левая рудная настенная панель 3",
    "Left Ore Wall Panel 4": "Левая рудная настенная панель 4",
    "Legends of the Tang Dynasty": "Легенды династии Тан",
    "Luna – Who Knows Not of the Truth": "Луна — не ведающая правды",
    "Mercury Thistle": "Чертополох меркурия",
    "Museum of the Year": "Музей года",
    "Natural Wood Wardrobe Horizontal Panel": "Горизонтальная панель деревянного гардероба",
    "New Species Discovery": "Открытие нового вида",
    "Panel TV Stand": "Стойка для панельного телевизора",
    "People on the Edge of the City": "Люди на окраине города",
    "Photo of the Deceased": "Фото усопшего",
    "Photo of the Holy Mother": "Фото святой матери",
    "Physalis Lantern Fruit": "Плод физалиса-фонарика",
    "Physical Properties of Baking Ingredients": "Физические свойства ингредиентов для выпечки",
    "Portrait Of The Former Curator": "Портрет бывшего куратора",
    "Portrait Of The Mayor": "Портрет мэра",
    "Prehistoric Animal Album": "Альбом доисторических животных",
    "Purple Hand Soap In The Jewelry Shop": "Фиолетовое мыло в ювелирном магазине",
    "Rosewood Porcelain Panel Screen": "Ширма из палисандрового фарфора",
    "Room Of The End": "Комната конца",
    "Statue of the Saint": "Статуя святого",
    "The Alchemist": "Алхимик",
    "The Arcane Codex: Magic and Herbs": "Арканический кодекс: магия и травы",
    "The Black Cat Thriller Collection": "Коллекция триллеров «Чёрный кот»",
    "The Black Crown": "Чёрная корона",
    "The Black Iron Apartments": "Чёрные железные апартаменты",
    "The End of Eternity": "Конец вечности",
    "The Farmer's Universe": "Вселенная фермера",
    "The Festival of Spirits Banner": "Баннер фестиваля крепкого алкоголя",
    "The Girl": "Девушка",
    "The Girl – Pet Verified": "Девушка — одобрено питомцами",
    "The Golden Age": "Золотой век",
    "The Gourmet's Guide to Baking – Volume I": "Гид гурмана по выпечке — том I",
    "The Gourmet's Guide to Baking – Volume II": "Гид гурмана по выпечке — том II",
    "The Great Detective Paul Collection": "Коллекция великого детектива Пола",
    "The Holmes Case Files": "Дела Холмса",
    "The Holmes Case Files: Collected Edition": "Дела Холмса: полное издание",
    "The Legendary Story of the Buendía Family": "Легендарная история семьи Буэндиа",
    "The Lost Atlantis": "Затерянная Атлантида",
    "The Miracle of Staying Confident": "Чудо уверенности в себе",
    "The Mysterious Outsider": "Таинственный аутсайдер",
    "The Old Bookstore Murder": "Убийство в старом книжном",
    "The Owl Beneath the Moon": "Сова под луной",
    "The Painter Under the Moonlight": "Художник под луной",
    "The Pet Squad Series": "Серия «Звериный отряд»",
    "The Road to Redemption": "Дорога к искуплению",
    "The Science of Baking": "Наука выпечки",
    "The Soul of Baking": "Душа выпечки",
    "The Sparkletime Gateway": "Врата искрящегося времени",
    "The Train Murder Case": "Дело об убийстве в поезде",
    "The Wheat Murder Case": "Дело об убийстве с пшеницей",
    "The World Atlas of Herbs": "Всемирный атлас трав",
    "Totem Banner Of Unknown Life": "Тотемный баннер неизвестной жизни",
    "Underground Passage By The Park": "Подземный переход у парка",
    "Unknown Beaked Creature Skull": "Череп неизвестного клювоносного существа",
    "Unknown Fluid": "Неизвестная жидкость",
    "Unknown Prehistoric Creature Skull": "Череп неизвестного доисторического существа",
    "Unknown Skull Fossil": "Окаменелость неизвестного черепа",
    "Vinyl \"Floral Whisper\"": "Пластинка «Цветочный шёпот»",
    "Vinyl \"Green Whisper\"": "Пластинка «Зелёный шёпот»",
    "Vinyl \"Magic Whisper\"": "Пластинка «Магический шёпот»",
    "Vinyl \"The First Chapter\"": "Пластинка «Первая глава»",
    "Whisper Draft": "Черновик «Шёпот»",
    "Whisper Tech Festival First Prize": "Главный приз фестиваля «Шёпот Тех»",
    "White Cardboard Shelf Back Panel": "Задняя панель полки из белого картона",
    "Wisdom Milk": "Молоко мудрости",
    "Wisteria Purple Computer Case": "Системный блок цвета глицинии",
    "Wisteria Purple Keyboard": "Клавиатура цвета глицинии",
    "Wisteria Purple Monitor": "Монитор цвета глицинии",
    "Chalk Panel Cabinet": "Шкаф с меловой панелью",
    "Chalk Panel Corner Cabinet": "Угловой шкаф с меловой панелью",
    "Theory of Negative Energy": "Теория отрицательной энергии",
    "Theory of Time Travel": "Теория путешествий во времени",
    "Thermal Mug": "Термокружка",
    "Thermometer": "Термометр",
    "Thermos": "Термос",
    "Thought Experiment": "Мысленный эксперимент",
    "Three-Tier Shelf": "Трёхъярусная полка",
    "Thriller Reading List": "Список триллеров для чтения",
    "Time Capsule": "Капсула времени",
    "Time Portal (Ready)": "Портал времени (готов)",
    "Time Portal (To the Present)": "Портал времени (в настоящее)",
    "Time Warp Theory": "Теория искривления времени",
    "Tissue Box": "Коробка салфеток",
    "Toilet Brush": "Щётка для унитаза",
    "Toilet Cleaner": "Очиститель для унитаза",
    "Toilet Paper Holder Shelf": "Полка для туалетной бумаги",
    "Toilet Paper Roll": "Туалетная бумага",
    "Toilet Plunger": "Вантуз",
    "Tome of Witchcraft": "Том колдовства",
    "Tongsheng Bunny Carpet": "Ковёр «Тунгустовый кролик»",
    "Tonic Water": "Тонизирующая вода",
    "Tool Bucket": "Ведро для инструментов",
    "Toolbox": "Ящик для инструментов",
    "Tooth Fossil": "Окаменелость зуба",
    "Totem Banner Of Unknown Life": "Тотемный баннер неизвестной жизни",
    "Little Cat's Ghost": "Призрак котёнка",
    "Little Chestnut": "Маленький каштан",
    "Little Cow Plush": "Плюшевая коровка",
    "Little Elephant Doll": "Кукла-слоник",
    "Little Fox Plush": "Плюшевая лисица",
    "Little Lamb Plush": "Плюшевый ягнёнок",
    "Litter of Kittens Grandma Turned Into": "Бабушка, превращённая в выводок котят",
    "Listening Device": "Устройство для прослушивания",
    "Liquid Foundation": "Тональная основа",
    "Lint Roller": "Ролик для ворса",
    "Liver Support Stools": "Табуреты для поддержки печени",
    "Locked Door": "Запертая дверь",
    "Log Coffee Table": "Журнальный столик из бревна",
    "London Mystery Collection": "Лондонская коллекция тайн",
    "Long Flick Pajamas": "Длинные пижамные штаны",
    "Low Cabinet": "Низкий шкаф",
    "Low Watt Hair Dryer": "Фен малой мощности",
    "Lucky Cat Doorbell": "Дверной звонок «Счастливый кот»",
    "Luggage Bag": "Дорожная сумка",
    "Luna Looking Out the Window": "Луна смотрит в окно",
    "Luna Sitting On A Chair": "Луна сидит на стуле",
    "Luna Sleeping": "Луна спит",
    "Magic Circle": "Магический круг",
    "Magical Notes": "Магические записи",
    "Magnifying Glass": "Увеличительное стекло",
    "Mahjong Table": "Стол для маджонга",
    "Maid Costume Dress": "Платье горничной",
    "Main Door": "Главная дверь",
    "Makeup Box": "Косметичка",
    "Mammal Corpse": "Труп млекопитающего",
    "Mannequin": "Манекен",
    "Mansion Bathroom Floor": "Пол ванной в особняке",
    "Mansion Wash Basin": "Умывальник в особняке",
    "Measuring Cup": "Мерный стакан",
    "Measuring Cylinder": "Мерный цилиндр",
    "Mechanism (Damaged)": "Механизм (повреждён)",
    "Mechanism (Intact)": "Механизм (исправен)",
    "Medical Record": "Медицинская карта",
    "Medicine & Daily Supplies Packing Box": "Коробка с лекарствами и расходниками",
    "Medicine From the Organization": "Лекарство от организации",
    "Medicine Trolley": "Медицинская тележка",
    "Mayor": "Мэр",
    "Mattress": "Матрас",
    "Starry Purple Dumbbell": "Звёздная фиолетовая гантель",
    "Black Metal Storage Rack": "Чёрная металлическая стойка",
    "Black Metal Table": "Чёрный металлический стол",
    "Black Pants": "Чёрные брюки",
    "Black Plastic Stool": "Чёрный пластиковый табурет",
    "Black Plate": "Чёрная тарелка",
    "Black Shiba Figurine": "Фигурка чёрного сиба-ину",
    "Black Shiba Inu Wall Art": "Картина с чёрным сиба-ину",
    "Black Shiba Pillow": "Подушка с сиба-ину",
    "Black Tea": "Чёрный чай",
    "Black Toilet Base": "Чёрное основание унитаза",
    "Black Toilet Tank": "Чёрный бачок унитаза",
    "Black Wood Wicker Chair": "Чёрное плетёное кресло",
    "Black-and-White TV": "Чёрно-белый телевизор",
    "Black-Gold Electric Guitar": "Электрогитара чёрно-золотая",
    "Blackboard": "Классная доска",
    "Blacktea Teacup": "Чашка для чёрного чая",
    "Blacktea Teapot": "Заварочный чайник",
    "Blanket 6": "Одеяло 6",
    "Blinds": "Жалюзи",
    "Block Wall": "Блочная стена",
    "Blonde Girl Figurine": "Фигурка светловолосой девочки",
    "Blood glucose meter": "Глюкометр",
    "Blood-Pressure Relief Medication": "Препарат от давления",
    "Bloody Trash Can": "Окровавленная урна",
    "Blue Abstract Painting": "Синяя абстрактная картина",
    "Blue and White Porcelain": "Сине-белый фарфор",
    "Blue and White Porcelain Flowerpot": "Сине-белая фарфоровая кашпо",
    "Blue and White Porcelain Plate": "Сине-белая фарфоровая тарелка",
    "Blue and White Porcelain Saucer": "Сине-белое фарфоровое блюдце",
    "Blue And White Porcelain Teacup": "Сине-белая фарфоровая чашка",
    "Blue And White Porcelain Teapot": "Сине-белый фарфоровый чайник",
    "Blue And White Stool": "Сине-белый табурет",
    "Blue And White Tank Top": "Сине-белая майка",
    "Blue Backpack": "Синий рюкзак",
    "Blue Bass": "Синяя бас-гитара",
    "Blue Border Stone": "Синий бордюрный камень",
    "Blue Cell Figurine": "Фигурка синей клетки",
    "Blue Electric Guitar": "Синяя электрогитара",
    "Blue Empty Medicine Bottle": "Синяя пустая аптечная бутылка",
    "Blue Enamel Mug": "Синяя эмалированная кружка",
    "Blue Fishing Line": "Синяя леска",
    "Blue Fishing Rod": "Синяя удочка",
    "Blue Flower": "Синий цветок",
    "Blue Flower Glass Jar": "Стеклянная банка с синим цветком",
    "Blue Gem Slot on Wall": "Гнездо для синего камня на стене",
    "Blue Glasses Case": "Синий футляр для очков",
    "Blue Guy Figurine": "Фигурка синего парня",
    "Blue Knight Figurine": "Фигурка синего рыцаря",
    "Blue Laser Barrier": "Синий лазерный барьер",
    "Blue Long Cotton Towel": "Синее длинное хлопковое полотенце",
    "Blue long-staple cotton towel": "Синее длинноволокнистое полотенце",
    "Blue Morpho Butterfly Specimen": "Образец бабочки морфо",
    "Blue Old Bottle Cap": "Синяя старая крышка от бутылки",
    "Blue Ore Tissue Box": "Синяя коробка салфеток",
    "Blue Single Bed": "Синяя односпальная кровать",
    "Blue Small Tablecloth": "Синяя маленькая скатерть",
    "Blue Striped Absorbent Mat": "Синий полосатый впитывающий коврик",
    "Blue Sword Samurai Figurine": "Фигурка самурая с синим мечом",
    "Blue Umbrella": "Синий зонт",
    "Blue V-Shaped Electric Guitar": "Синяя V-образная электрогитара",
    "Blue-Black Bare Metal Wall Lamp": "Сине-чёрная настенная лампа",
    "Blue-Black Metal Camp Bed": "Сине-чёрная раскладушка",
    "Blue-Black Vintage Lampshade Metal Wall Lamp": "Сине-чёрная винтажная настенная лампа",
    "Blue-Gold Celebration Balloon": "Сине-золотой праздничный шар",
    "Blue-Gray Plush Carpet": "Сине-серый плюшевый ковёр",
    "Blue-Purple Antique Butterfly": "Сине-фиолетовая антикварная бабочка",
    "Blue-Purple Pillow": "Сине-фиолетовая подушка",
    "Blue-Violet Ore": "Сине-фиолетовая руда",
    "Blueberry Lychee Preserves": "Варенье из черники и личи",
    "Blueberry Plant Specimen": "Образец черники",
    "Blueberry Shampoo": "Шампунь с черникой",
    "Board": "Доска",
    "Boat 3": "Лодка 3",
    "Body lotion": "Лосьон для тела",
    "Body Wash": "Гель для душа",
    "Bomb Flower": "Цветок-бомба",
    "Bonfire": "Костёр",
    "Bookshelf Bottom Panel": "Нижняя панель книжного шкафа",
    "Bookshelf Left Panel": "Левая панель книжного шкафа",
    "Bookshelf Right Panel": "Правая панель книжного шкафа",
    "Bookshelf Top Panel": "Верхняя панель книжного шкафа",
    "Boots": "Сапоги",
    "Botanical Scented Tissue": "Ботанические ароматные салфетки",
    "Bottom Floor": "Нижний этаж",
    "Bottom Layer": "Нижний слой",
    "Box 2": "Коробка 2",
    "Box of Weights": "Набор гантелей",
    "Box Plant": "Растение в коробке",
    "Box Stool": "Табурет-коробка",
    "Boxwood Bedside Table": "Самшитовый прикроватный столик",
    "Boxwood Bookshelf": "Самшитовый книжный шкаф",
    "Boxwood Headboard": "Самшитовое изголовье",
    "Boxwood Single Bed": "Самшитовая односпальная кровать",
    "Braised Beef Flavored Instant Ramen": "Лапша со вкусом тушёной говядины",
    "Branch": "Ветка",
    "Branch with Pinecones": "Ветка с шишками",
    "Brandy": "Бренди",
    "Brass Bulb Floor Lamp": "Латунный торшер",
    "Brass Candle Holder": "Латунный подсвечник",
    "Brass Curved Wall Lamp": "Латунная настенная лампа",
    "Brass Elegant Candle Holder": "Латунный изящный подсвечник",
    "Brass Hollow Wall Lamp": "Латунная полая настенная лампа",
    "Brass Metal Towel Bar": "Латунная полка для полотенец",
    "Brazil Banana": "Бразильский банан",
    "Bread Basket": "Хлебная корзина",
    "Bread Pillow": "Подушка-хлеб",
    "Bread Waist Cushion": "Поясничная подушка-хлеб",
    "Breathing Light Gaming Headset": "Игровая гарнитура с подсветкой",
    "Breeze Double Window": "Двустворчатое окно",
    "Brick Phone": "Кирпичный телефон",
    "Brick Red Hardcover Book": "Книга в кирпично-красной обложке",
    "Brick Wall Partition": "Кирпичная перегородка",
    "Brick-red Hanging Shelf": "Подвесная полка кирпичного цвета",
    "Bridge Travel Postcard": "Открытка с мостом",
    "Bright Sitting on Chair in Thought (Luna Ending)": "Брайт в раздумьях (финал Луны)",
    "Bright Yellow Desktop Speaker": "Ярко-жёлтая колонка",
    "Bright Yellow Hanging Rack": "Ярко-жёлтая подвесная полка",
    "Broccoli": "Брокколи",
    "Broccoli Produce Basket": "Корзина с брокколи",
    "Brochure": "Брошюра",
    "Broken Branch": "Сломанная ветка",
    "Broken Brick": "Сломанный кирпич",
    "Broken Bricks": "Битый кирпич",
    "Broken Cabinet (Furniture Store)": "Сломанный шкаф (магазин мебели)",
    "Broken Chair": "Сломанный стул",
    "Broken Chair (Furniture Store)": "Сломанный стул (магазин мебели)",
    "Broken Coffee Table (Furniture Store)": "Сломанный журнальный столик (магазин мебели)",
    "Broken Glass 1": "Разбитое стекло 1",
    "Broken Glass 2": "Разбитое стекло 2",
    "Broken Glass 3": "Разбитое стекло 3",
    "Broken Glass 4": "Разбитое стекло 4",
    "Broken Pallet (Furniture Store)": "Сломанный поддон (магазин мебели)",
    "Broken Sofa (Furniture Store)": "Сломанный диван (магазин мебели)",
    "Broken Square Table (Furniture Store)": "Сломанный квадратный стол (магазин мебели)",
    "Broken Stone": "Разбитый камень",
    "Broken Stool (Furniture Store)": "Сломанный табурет (магазин мебели)",
    "Broken Table": "Сломанный стол",
    "Broken Table (Furniture Store)": "Сломанный стол (магазин мебели)",
    "Bronze Mask": "Бронзовая маска",
    "Bronze Tissue Box": "Бронзовая коробка салфеток",
    "Broom": "Метла",
    "Brown File Folder": "Коричневая папка",
    "Brown Glass Reagent Bottle": "Коричневая бутылка для реактивов",
    "Brown Vintage Double Leather Sofa": "Коричневый винтажный кожаный диван",
    "Bubble Alien Corpse 2": "Пузырчатый инопланетный труп 2",
    "Buckled Notebook": "Блокнот с пряжкой",
    "Bug Spray": "Спрей от насекомых",
    "Bullet Head Gravestone (Damaged)": "Надгробие «пуля» (повреждено)",
    "Bulletin Board": "Доска объявлений",
    "Bumper Pole": "Отбойный столб",
    "Bumper Pole 2": "Отбойный столб 2",
    "Bun Head": "Голова с пучком",
    "Bunny Backrest Leather Sofa": "Кожаный диван с ушами зайчика",
    "Bunny Clothing Store Owner": "Владелица магазина одежды «Зайчик»",
    "Bunny Ear Corner Railing": "Угловые перила с ушами зайчика",
    "Bunny Ear Railing": "Перила с ушами зайчика",
    "Bunny Ear Railing Corner Post": "Угловая стойка перил с ушами зайчика",
    "Bunny Ear Touchscreen Temperature Control Shower": "Душ с сенсорным управлением «Зайчик»",
    "Bunny Pillow": "Подушка-зайчик",
    "Bunny Plush": "Плюшевый зайчик",
    "Bunny Quilt": "Одеяло с зайчиками",
    "Burnt Ash 1": "Пепел 1",
    "Burnt Ash 2": "Пепел 2",
    "Burnt Ash 3": "Пепел 3",
    "Burnt Croissant": "Подгоревший круассан",
    "Burnt Dorayaki": "Подгоревший дораяки",
    "Burnt Egg Tart": "Подгоревший яичный тарт",
    "Burnt Palmier": "Подгоревшее пальмье",
    "Burnt Soft European Bread": "Подгоревший европейский хлеб",
    "Bus Stop": "Остановка",
    "Bus Stop Foot Panel": "Панель остановки",
    "Bus Stop Sign": "Знак остановки",
    "Bus Stop Sign (Left)": "Знак остановки (слева)",
    "Bush 1": "Куст 1",
    "Bush 2": "Куст 2",
    "Butter Coffee Maker": "Кофеварка «Масло»",
    "Butter Radio": "Радио «Масло»",
    "Butter Vacuum Cleaner": "Пылесос «Масло»",
    "Cabbage": "Капуста",
    "Cabbage Plush Toy": "Плюшевая капуста",
    "Cabinet 4": "Шкаф 4",
    "Cactus": "Кактус",
    "Cactus Ball": "Кактус-шар",
    "Cactus Seed (Discarded)": "Семя кактуса (выброшено)",
    "Cake Lamp": "Лампа-торт",
    "Cake Menu Board": "Таблица меню тортов",
    "Cake Mold": "Форма для торта",
    "Cake Stand": "Подставка для торта",
    "Cake Takeout Bag": "Пакет для торта",
    "Cake Wrapping Paper": "Упаковочная бумага для торта",
    "Calendar": "Календарь",
    "Calla Lily": "Калла",
    "Calligraphy Brush": "Кисть для каллиграфии",
    "Camel Color Striped Rug": "Полосатый коврик верблюжьего цвета",
    "Camel Glasses Case": "Футляр для очков верблюжьего цвета",
    "Camel Tile Coffee Table": "Журнальный столик с плиткой",
    "Camellia": "Камелия",
    "Camera": "Камера",
    "Camera Maintenance": "Обслуживание камеры",
    "Camping Basket": "Походная корзина",
    "Camping Box 1": "Походный ящик 1",
    "Camping Box 2": "Походный ящик 2",
    "Camping Box 3": "Походный ящик 3",
    "Camping Box 4": "Походный ящик 4",
    "Camping Chair": "Походный стул",
    "Camping Mat": "Походный коврик",
    "Camping Table": "Походный стол",
    "Candle 1": "Свеча 1",
    "Candle 2": "Свеча 2",
    "Candle 3": "Свеча 3",
    "Candle 4": "Свеча 4",
    "Candle 5": "Свеча 5",
    "Candle 6": "Свеча 6",
    "Candle Set": "Набор свечей",
    "Cane": "Трость",
    "Cane Shaft": "Ствол трости",
    "Canned Cat Food": "Консервы для кошек",
    "Canned Coffee": "Кофе в банке",
    "Canned Dog Food": "Консервы для собак",
    "Canned Flowers": "Консервированные цветы",
    "Canned Grapes": "Консервированный виноград",
    "Canned Lychees": "Консервированный личи",
    "Canned Nuts": "Консервированные орехи",
    "Canned Strawberries": "Консервированная клубника",
    "Capri Blue File Box": "Файловая коробка цвета Капри",
    "Capri Blue Hunting Coat": "Охотничье пальто цвета Капри",
    "Capsule Coffee": "Капсульный кофе",
    "Car of Foolishness": "Машина глупцов",
    "Carbon Black Gothic Bed": "Готическая кровать угольно-чёрная",
    "Carbon Black Gothic Chair": "Готический стул угольно-чёрный",
    "Cream White TV Cabinet": "Шкаф для телевизора кремового цвета",
    "Carbon Black Long-Pile Carpet": "Угольно-чёрный длинноворсовый ковёр",
    "Cardboard Bed": "Картонная кровать",
    "Cardboard Box": "Картонная коробка",
    "Back of Computer Case": "Задняя панель системного блока",
    "Back of Mouse": "Задняя часть мыши",
    "Back of Sofa 6": "Тыльная сторона дивана 6",
    "Back of Television": "Задняя панель телевизора",
    "Bag of Almond Powder": "Пакет миндальной муки",
    "Bag of Baking Powder": "Пакет разрыхлителя",
    "Bag of Cocoa Powder": "Пакет какао",
    "Bag of Flour": "Пакет муки",
    "Bag of Milk Powder": "Пакет сухого молока",
    "Bag of Sugar": "Пакет сахара",
    "Bagua Sapling": "Саженец багуа",
    "Bagua Tree": "Дерево багуа",
    "Baked Croissant": "Выпеченный круассан",
    "Baked Dorayaki": "Выпеченный дораяки",
    "Baked Egg Tart": "Выпеченный яичный тарт",
    "Baked Palmier": "Выпеченное пальмье",
    "Baked Soft European Bread": "Выпеченный европейский хлеб",
    "Bakery Gift Box": "Подарочная коробка пекарни",
    "Bakery to Exterior": "Из пекарни наружу",
    "Baking Brush": "Кисть для выпечки",
    "Baking Tray": "Противень",
    "Balance Scale": "Весы",
    "Balcony to Bedroom – Home Unit 2": "С балкона в спальню — блок 2",
    "Ball Lightning": "Шаровая молния",
    "Ball Sewn From Fabric Scraps": "Мяч из лоскутков",
    "Bamboo Umbrella Stand": "Подставка для зонтов из бамбука",
    "Banana Peel": "Банановая кожура",
    "Bandit King": "Король разбойников",
    "Bar counter with ambient light": "Барная стойка с подсветкой",
    "Bar Neon Blackboard": "Неоновая вывеска бара",
    "Barbie Pink Single Bed": "Односпальная кровать цвета Барби",
    "Barnacle on Underground Wall 1": "Моллюск на подземной стене 1",
    "Barnacle on Underground Wall 2": "Моллюск на подземной стене 2",
    "Barnacle on Underground Wall 3": "Моллюск на подземной стене 3",
    "Barnacle on Underground Wall 4": "Моллюск на подземной стене 4",
    "Barnacle on Underground Wall 5": "Моллюск на подземной стене 5",
    "Basement Entrance Blocked by Planks": "Вход в подвал забит досками",
    "Basement Switch": "Выключатель в подвале",
    "Basic Rubber Boots": "Прочные резиновые сапоги",
    "Basic Sponge": "Обычная губка",
    "Basic White Plastic Clothes Hanger": "Белая пластиковая вешалка",
    "Basket Full of Flowers": "Корзина цветов",
    "Basket Full of Fruit": "Корзина фруктов",
    "Basket Full of Pinecones": "Корзина шишек",
    "Basketball Court": "Баскетбольная площадка",
    "Basketball Court Fence A1": "Ограда площадки A1",
    "Basketball Court Fence A5": "Ограда площадки A5",
    "Basketball Court Fence A6": "Ограда площадки A6",
    "Bass Guitar": "Бас-гитара",
    "Bathroom (Complete)": "Ванная (полная)",
    "Bathroom Divider Panel": "Разделительная панель ванной",
    "Bathroom Miscellaneous Packing Box": "Коробка с мелочами для ванной",
    "Bathroom to Dining Room – Home Unit 2": "Из ванной в столовую — блок 2",
    "Bathroom to Living Room": "Из ванной в гостиную",
    "Bathroom to Ward": "Из ванной в палату",
    "Battle for the Inheritance": "Борьба за наследство",
    "BBQ Flavored Chips (Bag)": "Чипсы со вкусом барбекю",
    "Beach-Colored Pillow": "Подушка цвета песка",
    "Bedroom to Balcony – Home Unit 2": "Из спальни на балкон — блок 2",
    "Bedroom to Dining Room – Home Unit 2": "Из спальни в столовую — блок 2",
    "Bedroom to Hallway": "Из спальни в коридор",
    "Bedroom to Secret Room": "Из спальни в тайную комнату",
    "Bedside Table 2": "Тумбочка 2",
    "Beef Jerky": "Вяленая говядина",
    "Beige 3-Seater Sofa": "Бежевый трёхместный диван",
    "Beige Apron": "Бежевый фартук",
    "Beige patterned long carpet": "Бежевый длинный ковёр с узором",
    "Beige Wooden Shoe Cabinet": "Бежевый деревянный обувной шкаф",
    "Beige-Gray Ceramic Sink Storage Cabinet Vertical 1": "Бежево-серый керамический шкаф 1",
    "Beige-Gray Ceramic Sink Storage Cabinet Vertical 2": "Бежево-серый керамический шкаф 2",
    "Bento Box": "Бэнто",
    "Bergamot Perfume": "Духи с бергамотом",
    "Beverage Dispenser": "Диспенсер для напитков",
    "Big Bottle of Fish Food": "Большая бутылка корма для рыб",
    "Big Mouth Speaker": "Колонка «Большой рот»",
    "Bird Album": "Альбом с птицами",
    "Bird's Nest Fern": "Папоротник «птичье гнездо»",
    "Birthday Banner": "Праздничный баннер",
    "Black and Gold Electric Guitar": "Чёрно-золотая электрогитара",
    "Black and Gold Guitar": "Чёрно-золотая гитара",
    "Black and Red Checkerboard Rug": "Чёрно-красный коврик в клетку",
    "Black Ceramic Rinse Cup": "Чёрная керамическая кружка для полоскания",
    "Black File Folder": "Чёрная папка",
    "Black Goji Nourishing Shampoo": "Шампунь с ягодой годжи",
    "Black Lacquered Desk Lamp": "Чёрная лакированная настольная лампа",
    "Black Lacquered Retro Refrigerator": "Чёрный лакированный ретро-холодильник",
    "Cream White Bar Counter Table": "Барная стойка кремового цвета",
    "Agatha": "Агата",
    "Anna": "Анна",
    "Brett": "Бретт",
    "Brett (After Kidnapping)": "Бретт (после похищения)",
    "Brett (After Kidnapping) 2": "Бретт (после похищения) 2",
    "Brett (After Kidnapping) 3": "Бретт (после похищения) 3",
    "Brett (After Kidnapping) 4": "Бретт (после похищения) 4",
    "Brett (Appears After All Rooms Are Done)": "Бретт (появляется после всех комнат)",
    "Brett (Appears After Ending)": "Бретт (после концовки)",
    "Brett (Appears After Museum)": "Бретт (после музея)",
    "Brett (Jewelry Shop)": "Бретт (ювелирный магазин)",
    "Brett (Press Office)": "Бретт (пресс-офис)",
    "Air Conditioner": "Кондиционер",
    "Display Stand": "Стойка для экспонатов",
    "Product Basket": "Корзина для товаров",
    "Furniture Display Stand": "Стойка для мебели",
    "Convenience Store": "Минимаркет",
    "Single Mattress": "Односпальный матрас",
    "Projection Screen": "Экран для проектора",
    "Big TV": "Большой телевизор",
    "52-Inch Big TV": "Большой телевизор 52 дюйма",
    "Freeze-Dried Chicken": "Сублимированная курица",
    "Plush Rug": "Плюшевый коврик",
    "A bundle of rope": "Моток верёвки",
    "A Page of Notes": "Листок с записями",
    "A Plate of Cake": "Тарелка с пирожным",
    "A Large Pipe": "Большая труба",
    "Abandoned Bed": "Заброшенная кровать",
    "Academic Book Set": "Набор учебников",
    "Acid Nutrient Fluid": "Кислотный питательный раствор",
    "Ad Board": "Рекламный щит",
    "African Violet": "Сенполия",
    "African Violet Growth Stage": "Сенполия (рост)",
    "African Violet Seed": "Семена сенполии",
    "Aged Wine": "Выдержанное вино",
    "Aged Copper Metal Bucket": "Медное ведро со следами возраста",
    "Alchemist's Lab Notes": "Записи алхимика",
    "Alien Flower": "Инопланетный цветок",
    "Alien Seed": "Инопланетное семя",
    "Alien Soil": "Инопланетная почва",
    "All-in-One Pet Bowl": "Миска для питомца 2-в-1",
    "Alpaca Storage Stool": "Пуфик-альпака с полкой",
    "Altar Offering Table": "Поминальный столик",
    "Amethyst": "Аметист",
    "Amethyst Crystal Ball": "Хрустальный шар из аметиста",
    "Air Conditioner": "Кондиционер",
    "Ancient Scroll": "Древний свиток",
    "Apple": "Яблоко",
    "Bathroom": "Ванная",
    "Bathtub": "Ванна",
    "Bedroom": "Спальня",
    "Bookshelf": "Книжный шкаф",
    "Cabinet": "Шкаф",
    "Chair": "Стул",
    "Coffee Table": "Журнальный столик",
    "Couch": "Диван",
    "Desk": "Письменный стол",
    "Dining Table": "Обеденный стол",
    "Double Sofa": "Двухместный диван",
    "Floor Lamp": "Торшер",
    "Flower": "Цветок",
    "Fridge": "Холодильник",
    "Refrigerator": "Холодильник",
    "Kitchen": "Кухня",
    "Living Room": "Гостиная",
    "Mirror": "Зеркало",
    "Shelf": "Полка",
    "Sink": "Раковина",
    "Sofa": "Диван",
    "Stool": "Табурет",
    "Table": "Стол",
    "Toilet": "Унитаз",
    "TV": "Телевизор",
    "Washing Machine": "Стиральная машина",
    "Window": "Окно",
    "Wooden Chair": "Деревянный стул",
    "Wooden Table": "Деревянный стол",
    "Wooden Shelf": "Деревянная полка",
    "White Chair": "Белый стул",
    "White Table": "Белый стол",
    "Single Bed": "Односпальная кровать",
    "Double Bed": "Двуспальная кровать",
    "Bookshelf": "Книжная полка",
    "Garden": "Сад",
    "Graveyard": "Кладбище",
    "Park": "Парк",
    "Museum": "Музей",
    "Shop": "Магазин",
    "Store": "Магазин",
    "Office": "Офис",
    "Lab": "Лаборатория",
    "Workshop": "Мастерская",
    "Bed": "Кровать",
    "Rug": "Коврик",
    "Carpet": "Ковёр",
    "Lamp": "Лампа",
    "Clock": "Часы",
    "Picture": "Картина",
    "Painting": "Картина",
    "Poster": "Постер",
    "Plant": "Растение",
    "Flower Pot": "Цветочный горшок",
    "Vase": "Ваза",
    "Book": "Книга",
    "Box": "Коробка",
    "Basket": "Корзина",
    "Bowl": "Миска",
    "Cup": "Чашка",
    "Plate": "Тарелка",
    "Bottle": "Бутылка",
    "Jar": "Банка",
    "Can": "Банка",
    "Bag": "Сумка",
    "Trash Can": "Мусорная корзина",
    "Wardrobe": "Гардероб",
    "Drawer": "Ящик",
    "Door": "Дверь",
    "Wall": "Стена",
    "Floor": "Пол",
    "Ceiling": "Потолок",
    "Railing": "Перила",
    "Stairs": "Лестница",
    "Fence": "Забор",
    "Gate": "Ворота",
    "Path": "Дорожка",
    "Tree": "Дерево",
    "Grass": "Трава",
    "Bush": "Куст",
    "Shrub": "Кустарник",
    "Seed": "Семя",
    "Seed Stage": "Стадия семени",
    "Growth Stage": "Стадия роста",
    "Sapling": "Саженец",
    "Fossil": "Окаменелость",
    "Sculpture": "Скульптура",
    "Figurine": "Фигурка",
    "Trophy": "Трофей",
    "Award": "Награда",
    "Record": "Пластинка",
    "Vinyl Record": "Виниловая пластинка",
    "Guitar": "Гитара",
    "Piano": "Пианино",
    "Drum": "Барабан",
    "Speaker": "Колонка",
    "Microphone": "Микрофон",
    "Camera": "Камера",
    "Computer": "Компьютер",
    "Monitor": "Монитор",
    "Keyboard": "Клавиатура",
    "Mouse": "Мышь",
    "Phone": "Телефон",
    "Radio": "Радио",
    "Fan": "Вентилятор",
    "Heater": "Обогреватель",
    "Oven": "Духовка",
    "Stove": "Плита",
    "Kettle": "Чайник",
    "Toaster": "Тостер",
    "Blender": "Блендер",
    "Microwave": "Микроволновка",
    "Dishwasher": "Посудомоечная машина",
    "Vacuum": "Пылесос",
    "Iron": "Утюг",
    "Broom": "Метла",
    "Mop": "Швабра",
    "Brush": "Щётка",
    "Towel": "Полотенце",
    "Soap": "Мыло",
    "Shampoo": "Шампунь",
    "Toothbrush": "Зубная щётка",
    "Pillow": "Подушка",
    "Blanket": "Одеяло",
    "Quilt": "Стеганое одеяло",
    "Sheet": "Простыня",
    "Curtain": "Штора",
    "Blinds": "Жалюзи",
    "Cushion": "Подушка",
    "Mat": "Коврик",
    "Hanger": "Вешалка",
    "Shoe Rack": "Обувная полка",
    "Umbrella": "Зонт",
    "Umbrella Stand": "Подставка для зонтов",
    "Newspaper": "Газета",
    "Magazine": "Журнал",
    "Letter": "Письмо",
    "Envelope": "Конверт",
    "Note": "Записка",
    "Diary": "Дневник",
    "Scroll": "Свиток",
    "Map": "Карта",
    "Globe": "Глобус",
    "Compass": "Компас",
    "Binoculars": "Бинокль",
    "Telescope": "Телескоп",
    "Microscope": "Микроскоп",
    "Tool": "Инструмент",
    "Hammer": "Молоток",
    "Screwdriver": "Отвёртка",
    "Wrench": "Гаечный ключ",
    "Scissors": "Ножницы",
    "Knife": "Нож",
    "Fork": "Вилка",
    "Spoon": "Ложка",
    "Cutting Board": "Разделочная доска",
    "Pot": "Кастрюля",
    "Pan": "Сковорода",
    "Ladle": "Половник",
    "Bottle": "Бутылка",
    "Jug": "Кувшин",
    "Glass": "Стакан",
    "Mug": "Кружка",
    "Teacup": "Чашка для чая",
    "Coffee Cup": "Кофейная чашка",
    "Wine Glass": "Бокал для вина",
    "Candle": "Свеча",
    "Candelabra": "Канделябр",
    "Vase": "Ваза",
    "Frame": "Рамка",
    "Photo Frame": "Фоторамка",
    "Mirror": "Зеркало",
    "Clock": "Часы",
    "Wall Clock": "Настенные часы",
    "Alarm Clock": "Будильник",
    "Grandfather Clock": "Напольные часы",
    "Chandelier": "Люстра",
    "Ceiling Light": "Потолочный светильник",
    "Desk Lamp": "Настольная лампа",
    "Floor Lamp": "Торшер",
    "Nightstand": "Тумбочка",
    "Dresser": "Комод",
    "Chest": "Сундук",
    "Trunk": "Сундук",
    "Barrel": "Бочка",
    "Crate": "Ящик",
    "Bucket": "Ведро",
    "Basket": "Корзина",
    "Hamper": "Корзина для белья",
    "Wastebasket": "Корзина для мусора",
    "Recycling Bin": "Контейнер для вторсырья",
    "Pet Bowl": "Миска для питомца",
    "Bird Cage": "Клетка для птицы",
    "Aquarium": "Аквариум",
    "Fountain": "Фонтан",
    "Well": "Колодец",
    "Fireplace": "Камин",
    "Stove": "Печь",
    "Grill": "Гриль",
    "Barbecue": "Мангал",
    "Picnic Table": "Стол для пикника",
    "Bench": "Скамейка",
    "Swing": "Качели",
    "Hammock": "Гамак",
    "Parasol": "Зонт от солнца",
    "Gazebo": "Беседка",
    "Fence": "Забор",
    "Gate": "Ворота",
    "Mailbox": "Почтовый ящик",
    "Doormat": "Коврик у двери",
    "Welcome Mat": "Коврик «Добро пожаловать»",
    "Key": "Ключ",
    "Lock": "Замок",
    "Bell": "Колокольчик",
    "Knocker": "Дверной молоток",
    "Lantern": "Фонарь",
    "Flashlight": "Фонарик",
    "Candle Holder": "Подсвечник",
    "Incense": "Благовония",
    "Incense Burner": "Курильница",
    "Vase": "Ваза",
    "Pottery": "Керамика",
    "Ceramic": "Керамический",
    "Porcelain": "Фарфор",
    "Glass": "Стекло",
    "Crystal": "Хрусталь",
    "Wooden": "Деревянный",
    "Metal": "Металлический",
    "Iron": "Железный",
    "Copper": "Медный",
    "Bronze": "Бронзовый",
    "Silver": "Серебряный",
    "Gold": "Золотой",
    "White": "Белый",
    "Black": "Чёрный",
    "Red": "Красный",
    "Blue": "Синий",
    "Green": "Зелёный",
    "Yellow": "Жёлтый",
    "Brown": "Коричневый",
    "Gray": "Серый",
    "Grey": "Серый",
    "Beige": "Бежевый",
    "Pink": "Розовый",
    "Purple": "Фиолетовый",
    "Orange": "Оранжевый",
    "Small": "Маленький",
    "Large": "Большой",
    "Big": "Большой",
    "Long": "Длинный",
    "Short": "Короткий",
    "Round": "Круглый",
    "Square": "Квадратный",
    "Rectangular": "Прямоугольный",
    "Old": "Старый",
    "Antique": "Антикварный",
    "Vintage": "Винтажный",
    "Modern": "Современный",
    "Classic": "Классический",
    "Rustic": "Деревенский",
    "Mini": "Мини",
    "Double": "Двухместный",
    "Single": "Односпальный",
    "Triple": "Трёхместный",
    "Folding": "Складной",
    "Hanging": "Подвесной",
    "Wall-Mounted": "Настенный",
    "Floor Standing": "Напольный",
    "Table Top": "Настольный",
    "Display": "Витрина",
    "Storage": "Для хранения",
    "Storage Box": "Коробка для хранения",
    "Storage Shelf": "Полка для хранения",
    "Storage Cabinet": "Шкаф для хранения",
    "Storage Basket": "Корзина для хранения",
    "Empty": "Пустой",
    "Full": "Полный",
    "Broken": "Сломанный",
    "Damaged": "Повреждённый",
    "Worn": "Поношенный",
    "New": "Новый",
    "Clean": "Чистый",
    "Dirty": "Грязный",
    "Open": "Открытый",
    "Closed": "Закрытый",
    "Left": "Левый",
    "Right": "Правый",
    "Top": "Верхний",
    "Bottom": "Нижний",
    "Middle": "Средний",
    "Corner": "Угловой",
    "Side": "Боковой",
    "Center": "Центральный",
    "Front": "Передний",
    "Back": "Задний",
    "Outdoor": "Уличный",
    "Indoor": "Комнатный",
    "Garden": "Садовый",
    "Kitchen": "Кухонный",
    "Bathroom": "Ванный",
    "Bedroom": "Спальный",
    "Living Room": "Гостиный",
    "Office": "Офисный",
    "Study": "Рабочий",
    "Kids": "Детский",
    "Pet": "Для питомцев",
    "Baby": "Детский",
    "Electric": "Электрический",
    "Electronic": "Электронный",
    "Manual": "Ручной",
    "Automatic": "Автоматический",
    "Portable": "Портативный",
    "Handheld": "Ручной",
    "Wireless": "Беспроводной",
    "Vintage": "Винтажный",
    "Retro": "Ретро",
    "Decorative": "Декоративный",
    "Functional": "Функциональный",
    "Antique": "Антикварный",
    "Traditional": "Традиционный",
    "Contemporary": "Современный",
    "Minimalist": "Минималистичный",
    "Bohemian": "Богемный",
    "Industrial": "Индустриальный",
    "Scandinavian": "Скандинавский",
    "Japanese": "Японский",
    "Chinese": "Китайский",
    "European": "Европейский",
    "American": "Американский",
    "Mediterranean": "Средиземноморский",
    "Tropical": "Тропический",
    "Ocean": "Океанский",
    "Sea": "Морской",
    "Beach": "Пляжный",
    "Forest": "Лесной",
    "Mountain": "Горный",
    "Desert": "Пустынный",
    "Urban": "Городской",
    "Rural": "Сельский",
    "Country": "Деревенский",
    "Coastal": "Прибрежный",
    "Island": "Островной",
    "Tropical": "Тропический",
    "Winter": "Зимний",
    "Summer": "Летний",
    "Spring": "Весенний",
    "Autumn": "Осенний",
    "Fall": "Осенний",
    "Christmas": "Рождественский",
    "Halloween": "Хэллоуин",
    "Easter": "Пасхальный",
    "Birthday": "День рождения",
    "Wedding": "Свадебный",
    "Funeral": "Похоронный",
    "Memorial": "Поминальный",
    "Religious": "Религиозный",
    "Spiritual": "Духовный",
    "Mystical": "Мистический",
    "Magic": "Магический",
    "Alchemical": "Алхимический",
    "Scientific": "Научный",
    "Medical": "Медицинский",
    "Artistic": "Художественный",
    "Musical": "Музыкальный",
    "Literary": "Литературный",
    "Historical": "Исторический",
    "Mythological": "Мифологический",
    "Fantasy": "Фэнтези",
    "Sci-Fi": "Научная фантастика",
    "Steampunk": "Стимпанк",
    "Gothic": "Готический",
    "Victorian": "Викторианский",
    "Edwardian": "Эдвардианский",
    "Art Deco": "Ар-деко",
    "Art Nouveau": "Ар-нуво",
    "Baroque": "Барокко",
    "Rococo": "Рококо",
    "Renaissance": "Ренессанс",
    "Colonial": "Колониальный",
    "Farmhouse": "Фермерский",
    "Cottage": "Коттеджный",
    "Cabin": "Домик",
    "Lodge": "Лодж",
    "Villa": "Вилла",
    "Mansion": "Особняк",
    "Castle": "Замок",
    "Palace": "Дворец",
    "Temple": "Храм",
    "Church": "Церковь",
    "Cathedral": "Собор",
    "Monastery": "Монастырь",
    "Shrine": "Святилище",
    "Altar": "Алтарь",
    "Tomb": "Гробница",
    "Grave": "Могила",
    "Tombstone": "Надгробие",
    "Gravestone": "Надгробный камень",
    "Cemetery": "Кладбище",
    "Mausoleum": "Мавзолей",
    "Crypt": "Склеп",
    "Coffin": "Гроб",
    "Urn": "Урна",
    "Wreath": "Венок",
    "Bouquet": "Букет",
    "Flower Arrangement": "Композиция из цветов",
    "Potted Plant": "Растение в горшке",
    "Succulent": "Сукулент",
    "Cactus": "Кактус",
    "Fern": "Папоротник",
    "Palm": "Пальма",
    "Bonsai": "Бонсай",
    "Orchid": "Орхидея",
    "Rose": "Роза",
    "Tulip": "Тюльпан",
    "Daisy": "Ромашка",
    "Sunflower": "Подсолнух",
    "Lily": "Лилия",
    "Iris": "Ирис",
    "Lavender": "Лаванда",
    "Jasmine": "Жасмин",
    "Peony": "Пион",
    "Hydrangea": "Гортензия",
    "Daffodil": "Нарцисс",
    "Carnation": "Гвоздика",
    "Poppy": "Мак",
    "Violet": "Фиалка",
    "Dandelion": "Одуванчик",
    "Clover": "Клевер",
    "Moss": "Мох",
    "Ivy": "Плющ",
    "Vine": "Лоза",
    "Herb": "Трава",
    "Spice": "Специя",
    "Vegetable": "Овощ",
    "Fruit": "Фрукт",
    "Berry": "Ягода",
    "Nut": "Орех",
    "Grain": "Зерно",
    "Seed": "Семя",
    "Bean": "Боб",
    "Pea": "Горох",
    "Corn": "Кукуруза",
    "Wheat": "Пшеница",
    "Rice": "Рис",
    "Oat": "Овёс",
    "Barley": "Ячмень",
    "Rye": "Рожь",
    "Milk": "Молоко",
    "Cheese": "Сыр",
    "Butter": "Масло",
    "Cream": "Кремовый",
    "Yogurt": "Йогурт",
    "Egg": "Яйцо",
    "Bread": "Хлеб",
    "Toast": "Тост",
    "Croissant": "Круассан",
    "Bagel": "Бейгл",
    "Muffin": "Маффин",
    "Donut": "Пончик",
    "Cookie": "Печенье",
    "Cake": "Торт",
    "Pie": "Пирог",
    "Pudding": "Пудинг",
    "Ice Cream": "Мороженое",
    "Candy": "Конфета",
    "Chocolate": "Шоколад",
    "Honey": "Мёд",
    "Jam": "Варенье",
    "Sauce": "Соус",
    "Vinegar": "Уксус",
    "Oil": "Масло",
    "Salt": "Соль",
    "Sugar": "Сахар",
    "Pepper": "Перец",
    "Coffee": "Кофе",
    "Tea": "Чай",
    "Juice": "Сок",
    "Water": "Вода",
    "Wine": "Вино",
    "Beer": "Пиво",
    "Soda": "Газировка",
    "Cocktail": "Коктейль",
    "Whiskey": "Виски",
    "Vodka": "Водка",
    "Rum": "Ром",
    "Gin": "Джин",
    "Champagne": "Шампанское",
    "Liquor": "Ликёр",
    "Liqueur": "Ликёр",
    "Spirits": "Крепкий алкоголь",
    "Alcoholic": "Алкогольный",
    "Non-Alcoholic": "Безалкогольный",
    "Organic": "Органический",
    "Natural": "Натуральный",
    "Artificial": "Искусственный",
    "Synthetic": "Синтетический",
    "Recycled": "Переработанный",
    "Eco-Friendly": "Эко-дружелюбный",
    "Sustainable": "Устойчивый",
    "Biodegradable": "Биоразлагаемый",
    "Compostable": "Компостируемый",
    "Reusable": "Многоразовый",
    "Disposable": "Одноразовый",
    "Handmade": "Ручная работа",
    "Handcrafted": "Ручной работы",
    "Custom": "На заказ",
    "Personalized": "Персонализированный",
    "Limited Edition": "Лимитированная серия",
    "Collector's Edition": "Коллекционное издание",
    "Rare": "Редкий",
    "Unique": "Уникальный",
    "Exclusive": "Эксклюзивный",
    "Premium": "Премиум",
    "Luxury": "Люкс",
    "Deluxe": "Делюкс",
    "Standard": "Стандартный",
    "Basic": "Базовый",
    "Simple": "Простой",
    "Plain": "Простой",
    "Fancy": "Нарядный",
    "Elegant": "Элегантный",
    "Sophisticated": "Изысканный",
    "Rustic": "Деревенский",
    "Cozy": "Уютный",
    "Comfortable": "Удобный",
    "Practical": "Практичный",
    "Useful": "Полезный",
    "Decorative": "Декоративный",
    "Ornamental": "Декоративный",
    "Functional": "Функциональный",
    "Multi-Purpose": "Многофункциональный",
    "All-Purpose": "Универсальный",
    "Specialty": "Специальный",
    "Professional": "Профессиональный",
    "Commercial": "Коммерческий",
    "Industrial": "Промышленный",
    "Residential": "Жилой",
    "Institutional": "Институциональный",
    "Public": "Публичный",
    "Private": "Частный",
    "Personal": "Личный",
    "Family": "Семейный",
    "Guest": "Гостевой",
    "Master": "Главный",
    "Children's": "Детский",
    "Baby": "Детский",
    "Elderly": "Для пожилых",
    "Disabled": "Для инвалидов",
    "Unisex": "Унисекс",
    "Men's": "Мужской",
    "Women's": "Женский",
    "Boys": "Мальчиков",
    "Girls": "Девочек",
    "Unisex": "Унисекс",
}

# Слова для исправления кривой транслитерации (нет в основном WORDS)
WORDS_FIX_TRANSLIT = {
    "Chess": "Шахматный",
    "Chopstick": "Палочка",
    "Chopsticks": "Палочки для еды",
    "Chopping": "Разделочный",
    "Clothes": "Одежда",
    "Clothing": "Одежда",
    "Cloud": "Облако",
    "Chestnut": "Каштановый",
    "Citronella": "Цитронелла",
    "Chewy": "Жевательный",
    "Mints": "Мятные конфеты",
    "Chick": "Цыплёнок",
    "Scallions": "Зелёный лук",
    "Chopped": "Нарезанный",
    "Magical": "Магический",
    "Mahjong": "Маджонг",
    "Mechanism": "Механизм",
    "Measuring": "Измерительный",
    "Medicine": "Лекарство",
    "Confidential": "Конфиденциальный",
    "Goggles": "Защитные очки",
    "Lollipop": "Леденец",
    "Locked": "Запертая",
    "Little": "Маленький",
    "Ghost": "Призрак",
    "Cow": "Корова",
    "Fox": "Лиса",
    "Lamb": "Ягнёнок",
    "Elephant": "Слон",
    "Doll": "Кукла",
    "Listening": "Слушание",
    "Liquid": "Жидкость",
    "Foundation": "Основа",
    "Lint": "Ворс",
    "Roller": "Ролик",
    "Coated": "С покрытием",
    "Frying": "Для жарки",
    "Coconut": "Кокос",
    "Juice": "Сок",
    "Grounds": "Гуща",
    "Cold": "Холодный",
    "Devotion": "Преданность",
    "Collected": "Собранные",
    "Colorful": "Разноцветный",
    "Combat": "Боевой",
    "Condiment": "Приправа",
    "Confession": "Исповедь",
    "Craftsman": "Мастер",
    "Discount": "Скидка",
    "Main": "Главная",
    "Exhibit": "Экспонат",
    "Scene": "Сцена",
    "Stair": "Лестница",
    "Makeup": "Косметика",
    "Mammal": "Млекопитающее",
    "Corpse": "Труп",
    "Mannequin": "Манекен",
    "Mansion": "Особняк",
    "Wash": "Умывальник",
    "Basin": "Раковина",
    "Level": "Уровень",
    "Character": "Персонаж",
    "Archive": "Архив",
    "Text": "Текст",
    "Unaware": "Не ведающая",
    "Truth": "Правда",
    "Confused": "Смущённая",
    "Looking": "Смотрящая",
    "Sitting": "Сидящая",
    "Sleeping": "Спящая",
    "Lunar": "Лунный",
    "Rover": "Ровер",
    "Luncheon": "Обеденное",
    "Meat": "Мясо",
    "Mad": "Безумный",
    "Scientist": "Учёный",
    "Magnifying": "Увеличительное",
    "Lying": "Лежащая",
    "Standing": "Стоящая",
    "Tall": "Высокий",
    "Newsroom": "Редакция",
    "Maid": "Горничная",
    "Costume": "Костюм",
    "Dress": "Платье",
    "Mark": "Марка",
    "Current": "Текущее",
    "Generation": "Поколение",
    "Prototype": "Прототип",
    "Mascot": "Талисман",
    "Suit": "Костюм",
    "Masked": "В маске",
    "Mattress": "Матрас",
    "Starry": "Звёздный",
    "Purple": "Фиолетовый",
    "Dumbbell": "Гантель",
    "Cylinder": "Цилиндр",
    "Nursing": "Сестринский",
    "Pad": "Подушка",
    "Medical": "Медицинский",
    "Record": "Пластинка",
    "Daily": "Ежедневный",
    "Supplies": "Принадлежности",
    "Packing": "Упаковка",
    "From": "Из",
    "Organization": "Организации",
    "Trolley": "Тележка",
    "Acrylic": "Акриловый",
    "Restroom": "Туалет",
    "Diamond": "Алмаз",
    "Glasses": "Очки",
    "Holder": "Держатель",
    "Powder": "Порошок",
    "Sauce": "Соус",
    "Dictionary": "Словарь",
    "Geranium": "Герань",
    "Detective": "Детектив",
    "Movie": "Фильм",
    "Poster": "Постер",
    "Gunfight": "Перестрелка",
    "Hero": "Герой",
    "Thriller": "Триллер",
    "Collection": "Коллекция",
    "Potato": "Картофельные",
    "Chips": "Чипсы",
    "Haystack": "Сеновал",
    "File": "Файл",
    "Glass": "Стекло",
    "Notes": "Записи",
    "Circle": "Круг",
    "Placement": "Размещение",
    "Explanation": "Пояснение",
    "Wall": "Стена",
    "Nutrient": "Питательный",
    "Solution": "Раствор",
    "Octopus": "Осьминог",
    "Soil": "Почва",
    "Stain": "Пятно",
    "Wand": "Жезл",
    "Scrubbing": "Чистящий",
    "Closed": "Закрытый",
    "Suitcase": "Чемодан",
    "Clips": "Клипы",
    "CD": "CD",
    "Set": "Набор",
    "Clipping": "Вырезка",
    "Picture": "Картина",
    "Clothesline": "Бельевая верёвка",
    "Display": "Витрина",
    "Container": "Контейнер",
    "Alphabet": "Алфавит",
    "Flick": "Мерцание",
    "Sci-Fi": "Научная фантастика",
    "Stories": "Истории",
    "Short": "Короткий",
    "Test": "Тестовый",
    "Block": "Блок",
    "Comb": "Расчёска",
    "Haystack": "Сеновал",
    "Combo": "Комбо",
    "Storage": "Хранение",
    "Comedy": "Комедия",
    "Manga": "Манга",
    "Dishwashing": "Мытьё посуды",
    "Communication": "Связь",
    "Device": "Устройство",
    "Company": "Компания",
    "Staff": "Сотрудники",
    "Compiled": "Собранные",
    "Computer": "Компьютер",
    "Conch": "Раковина",
    "Concrete": "Бетон",
    "Surface": "Поверхность",
    "Condom": "Презерватив",
    "Confident": "Уверенный",
    "Conveyor": "Конвейер",
    "Cooker": "Плита",
    "Cooking": "Готовка",
    "Cool": "Прохладный",
    "Coral": "Коралл",
    "Corduroy": "Вельвет",
    "Cork": "Пробка",
    "Cornered": "Угловой",
    "Corners": "Углы",
    "Cosmic": "Космический",
    "Cosmos": "Космос",
    "Counter": "Стойка",
    "Countertop": "Столешница",
    "Cover": "Крышка",
    "Covered": "Покрытый",
    "Crab": "Краб",
    "Crack": "Трещина",
    "Crackers": "Крекеры",
    "Cradle": "Колыбель",
    "Crane": "Журавль",
    "Crate": "Ящик",
    "Crayon": "Карандаш",
    "Creamy": "Кремовый",
    "Creature": "Существо",
    "Creepy": "Жуткий",
    "Crimes": "Преступления",
    "Crimson": "Багровый",
    "Croissant": "Круассан",
    "Crown": "Корона",
    "Crucible": "Тигель",
    "Cruise": "Круиз",
    "Crumpled": "Смятый",
    "Crushed": "Раздавленный",
    "Crystal": "Хрусталь",
    "Cuba": "Куба",
    "Cultivation": "Выращивание",
    "Cupcake": "Кекс",
    "Curator": "Куратор",
    "Curious": "Любопытный",
    "Curling": "Кёрлинг",
    "Current": "Текущий",
    "Curtains": "Шторы",
    "Cushioned": "С мягкой обивкой",
    "Cutting": "Разделочный",
    "Cyan": "Бирюзовый",
    "Cyber": "Кибер",
    "Cylinder": "Цилиндр",
}

# Слова (для замены по словам в составных названиях)
WORDS = {
    "Wooden": "Деревянный",
    "White": "Белый",
    "Black": "Чёрный",
    "Red": "Красный",
    "Blue": "Синий",
    "Green": "Зелёный",
    "Yellow": "Жёлтый",
    "Brown": "Коричневый",
    "Gray": "Серый",
    "Grey": "Серый",
    "Beige": "Бежевый",
    "Pink": "Розовый",
    "Purple": "Фиолетовый",
    "Orange": "Оранжевый",
    "Small": "Маленький",
    "Large": "Большой",
    "Big": "Большой",
    "Round": "Круглый",
    "Square": "Квадратный",
    "Metal": "Металлический",
    "Plastic": "Пластиковый",
    "Glass": "Стеклянный",
    "Ceramic": "Керамический",
    "Stone": "Каменный",
    "Marble": "Мраморный",
    "Wood": "Дерево",
    "Chair": "Стул",
    "Table": "Стол",
    "Shelf": "Полка",
    "Desk": "Стол",
    "Bed": "Кровать",
    "Sofa": "Диван",
    "Lamp": "Лампа",
    "Mirror": "Зеркало",
    "Clock": "Часы",
    "Box": "Коробка",
    "Basket": "Корзина",
    "Cabinet": "Шкаф",
    "Stool": "Табурет",
    "Rug": "Коврик",
    "Carpet": "Ковёр",
    "Frame": "Рамка",
    "Stand": "Стойка",
    "Rack": "Стойка",
    "Hook": "Крючок",
    "Hanger": "Вешалка",
    "Tray": "Поднос",
    "Bowl": "Миска",
    "Cup": "Чашка",
    "Plate": "Тарелка",
    "Bottle": "Бутылка",
    "Jar": "Банка",
    "Pot": "Горшок",
    "Pan": "Сковорода",
    "Kettle": "Чайник",
    "Towel": "Полотенце",
    "Pillow": "Подушка",
    "Blanket": "Одеяло",
    "Curtain": "Штора",
    "Cushion": "Подушка",
    "Mat": "Коврик",
    "Brush": "Щётка",
    "Broom": "Метла",
    "Mop": "Швабра",
    "Shovel": "Лопата",
    "Scissors": "Ножницы",
    "Knife": "Нож",
    "Fork": "Вилка",
    "Spoon": "Ложка",
    "Book": "Книга",
    "Note": "Записка",
    "Letter": "Письмо",
    "Photo": "Фото",
    "Picture": "Картина",
    "Poster": "Постер",
    "Plant": "Растение",
    "Flower": "Цветок",
    "Tree": "Дерево",
    "Seed": "Семя",
    "Fossil": "Окаменелость",
    "Sculpture": "Скульптура",
    "Figurine": "Фигурка",
    "Model": "Модель",
    "Toy": "Игрушка",
    "Game": "Игра",
    "Tool": "Инструмент",
    "Device": "Устройство",
    "Machine": "Машина",
    "Equipment": "Оборудование",
    "Appliance": "Бытовая техника",
    "Furniture": "Мебель",
    "Decoration": "Украшение",
    "Accessory": "Аксессуар",
    "Item": "Предмет",
    "Object": "Объект",
    "Thing": "Вещь",
    "Piece": "Экземпляр",
    "Set": "Набор",
    "Collection": "Коллекция",
    "Pack": "Упаковка",
    "Bundle": "Связка",
    "Group": "Группа",
    "Pair": "Пара",
    "Dozen": "Дюжина",
    "Single": "Один",
    "Double": "Двойной",
    "Triple": "Тройной",
    "Multi": "Много",
    "Extra": "Дополнительный",
    "Mini": "Мини",
    "Micro": "Микро",
    "Maxi": "Макси",
    "Mega": "Мега",
    "Super": "Супер",
    "Ultra": "Ультра",
    "Hyper": "Гипер",
    "Pro": "Про",
    "Plus": "Плюс",
    "Premium": "Премиум",
    "Deluxe": "Делюкс",
    "Classic": "Классический",
    "Vintage": "Винтажный",
    "Retro": "Ретро",
    "Modern": "Современный",
    "Antique": "Антикварный",
    "Ancient": "Древний",
    "Old": "Старый",
    "New": "Новый",
    "Used": "Б/у",
    "Worn": "Поношенный",
    "Broken": "Сломанный",
    "Damaged": "Повреждённый",
    "Empty": "Пустой",
    "Full": "Полный",
    "Open": "Открытый",
    "Closed": "Закрытый",
    "Left": "Левый",
    "Right": "Правый",
    "Top": "Верхний",
    "Bottom": "Нижний",
    "Front": "Передний",
    "Back": "Задний",
    "Side": "Боковой",
    "Center": "Центральный",
    "Corner": "Угловой",
    "Wall": "Стена",
    "Floor": "Пол",
    "Ceiling": "Потолок",
    "Door": "Дверь",
    "Window": "Окно",
    "Gate": "Ворота",
    "Fence": "Забор",
    "Railing": "Перила",
    "Stairs": "Лестница",
    "Path": "Дорожка",
    "Entrance": "Вход",
    "Exit": "Выход",
    "Room": "Комната",
    "Hall": "Зал",
    "Office": "Офис",
    "Lab": "Лаборатория",
    "Shop": "Магазин",
    "Store": "Магазин",
    "Bar": "Бар",
    "Cafe": "Кафе",
    "Restaurant": "Ресторан",
    "Kitchen": "Кухня",
    "Bathroom": "Ванная",
    "Bedroom": "Спальня",
    "Living": "Гостиная",
    "Dining": "Обеденный",
    "Study": "Кабинет",
    "Library": "Библиотека",
    "Gallery": "Галерея",
    "Museum": "Музей",
    "Park": "Парк",
    "Garden": "Сад",
    "Yard": "Двор",
    "Courtyard": "Внутренний двор",
    "Balcony": "Балкон",
    "Terrace": "Терраса",
    "Patio": "Патио",
    "Porch": "Крыльцо",
    "Garage": "Гараж",
    "Basement": "Подвал",
    "Attic": "Чердак",
    "Loft": "Лофт",
    "Closet": "Гардеробная",
    "Pantry": "Кладовая",
    "Cellar": "Погреб",
    "Shed": "Сарай",
    "Barn": "Амбар",
    "Stable": "Конюшня",
    "Greenhouse": "Теплица",
    "Workshop": "Мастерская",
    "Studio": "Студия",
    "Atelier": "Ателье",
    "Salon": "Салон",
    "Spa": "Спа",
    "Gym": "Спортзал",
    "Pool": "Бассейн",
    "Court": "Корт",
    "Field": "Поле",
    "Track": "Трек",
    "Ring": "Ринг",
    "Stage": "Сцена",
    "Theater": "Театр",
    "Cinema": "Кинотеатр",
    "Concert": "Концерт",
    "Hall": "Зал",
    "Lobby": "Вестибюль",
    "Foyer": "Фойе",
    "Corridor": "Коридор",
    "Hallway": "Коридор",
    "Passage": "Проход",
    "Tunnel": "Туннель",
    "Bridge": "Мост",
    "Tower": "Башня",
    "Building": "Здание",
    "House": "Дом",
    "Home": "Дом",
    "Apartment": "Квартира",
    "Room": "Комната",
    "Unit": "Блок",
    "Section": "Секция",
    "Area": "Зона",
    "Zone": "Зона",
    "Space": "Пространство",
    "Place": "Место",
    "Spot": "Место",
    "Point": "Точка",
    "Location": "Локация",
    "Site": "Участок",
    "Ground": "Земля",
    "Land": "Земля",
    "Property": "Недвижимость",
    "Estate": "Имущество",
    "Residence": "Резиденция",
    "Dwelling": "Жилище",
    "Abode": "Обитель",
    "Shelter": "Убежище",
    "Haven": "Пристанище",
    "Refuge": "Убежище",
    "Sanctuary": "Святилище",
    "Shrine": "Святилище",
    "Temple": "Храм",
    "Church": "Церковь",
    "Cathedral": "Собор",
    "Chapel": "Часовня",
    "Altar": "Алтарь",
    "Shrine": "Святилище",
    "Pipe": "Труба",
    "Alchemist": "Алхимика",
    "Medium": "Средний",
    "Default": "По умолчанию",
    "Off": "Выкл.",
    "Negative": "Отрицательный",
    "Discarded": "Выброшенный",
    "Angel": "Ангел",
    "Anime": "Аниме",
    "Anthurium": "Антуриум",
    "Ore": "Руда",
    "Ape": "Обезьяна",
    "Bird": "Птица",
    "Cockpit": "Кабина",
    "Steering": "Рулевой",
    "Wheel": "Колесо",
    "Dinosaur": "Динозавр",
    "Dragonfly": "Стрекоза",
    "Insect": "Насекомое",
    "Jellyfish": "Медуза",
    "Jetpack": "Реактивный ранец",
    "Lamprey": "Минога",
    "Sea": "Морской",
    "Anemone": "Актиния",
    "Starfish": "Морская звезда",
    "Sword": "Меч",
    "Telephone": "Телефон",
    "Vine": "Лоза",
    "Cider": "Сидр",
    "Dress": "Платье",
    "Bath": "Ванна",
    "Slippers": "Шлёпанцы",
    "Astronomical": "Астрономический",
    "Feeder": "Кормушка",
    "Avocado": "Авокадо",
    "Bean": "Боб",
    "Bag": "Мешок",
    "Tablecloth": "Скатерть",
    "Two-Seater": "Двухместный",
    "Long-Staple": "Длинноволокнистый",
    "Lattice": "Решётка",
    "Slate": "Сланец",
    "Moth": "Бабочка",
    "Fern": "Папоротник",
    "Astrolabe": "Астролябия",
    "Astronaut": "Космонавт",
    "Arched": "Арочный",
    "Gravestone": "Надгробие",
    "Asparagus": "Спаржа",
    "Shiba": "Сиба",
    "Inu": "ину",
    "Toilet": "Унитаз",
    "Base": "Основание",
    "Tank": "Бачок",
    "Wicker": "Плетёный",
    "Bare": "Голый",
    "Camp": "Походный",
    "Lampshade": "Абажур",
    "Celebration": "Праздничный",
    "Balloon": "Шар",
    "Violet": "Фиолетовый",
    "Lychee": "Личи",
    "Preserves": "Варенье",
    "Bomb": "Бомба",
    "Panel": "Панель",
    "Botanical": "Ботанический",
    "Scented": "Ароматный",
    "Boxwood": "Самшитовый",
    "Bedside": "Прикроватный",
    "Headboard": "Изголовье",
    "Braised": "Тушёный",
    "Beef": "Говядина",
    "Flavored": "Со вкусом",
    "Instant": "Быстрорастворимый",
    "Ramen": "Лапша",
    "Pinecones": "Шишки",
    "Bulb": "Лампа",
    "Curved": "Изогнутый",
    "Hollow": "Полый",
    "Bar": "Полка",
    "Brazil": "Бразильский",
    "Banana": "Банан",
    "Waist": "Поясничный",
    "Breathing": "Дышащий",
    "Gaming": "Игровой",
    "Headset": "Гарнитура",
    "Breeze": "Бриз",
    "Hardcover": "В твёрдом переплёте",
    "Partition": "Перегородка",
    "Bridge": "Мост",
    "Travel": "Путешествие",
    "Postcard": "Открытка",
    "Thought": "Раздумье",
    "Luna": "Луна",
    "Ending": "Финал",
    "Desktop": "Настольный",
    "Produce": "Продукты",
    "Brochure": "Брошюра",
    "Pallet": "Поддон",
    "Reagent": "Реактив",
    "Buckled": "С пряжкой",
    "Bug": "Насекомое",
    "Spray": "Спрей",
    "Bullet": "Пуля",
    "Bulletin": "Объявлений",
    "Bumper": "Отбойный",
    "Pole": "Столб",
    "Backrest": "Спинка",
    "Touchscreen": "Сенсорный",
    "Temperature": "Температура",
    "Control": "Управление",
    "Shower": "Душ",
    "Dorayaki": "Дораяки",
    "Tart": "Тарт",
    "Palmier": "Пальмье",
    "European": "Европейский",
    "Foot": "Ножной",
    "Cabbage": "Капуста",
    "Mold": "Форма",
    "Takeout": "На вынос",
    "Wrapping": "Упаковочный",
    "Calla": "Калла",
    "Lily": "Лилия",
    "Calligraphy": "Каллиграфия",
    "Camel": "Верблюжий",
    "Striped": "Полосатый",
    "Maintenance": "Обслуживание",
    "Camping": "Походный",
    "Shaft": "Ствол",
    "Canned": "Консервированный",
    "Cat": "Кошка",
    "Dog": "Собака",
    "Grapes": "Виноград",
    "Lychees": "Личи",
    "Nuts": "Орехи",
    "Strawberries": "Клубника",
    "Capri": "Капри",
    "Hunting": "Охотничий",
    "Coat": "Пальто",
    "Capsule": "Капсульный",
    "Carbon": "Угольный",
    "Gothic": "Готический",
    "Loveseat": "Диванчик",
    "Armchair": "Кресло",
    "Recliner": "Кресло-реклайнер",
    "Ottoman": "Пуфик",
    "Maple": "Кленовый",
    "Fabric": "Тканевый",
    "Leather": "Кожаный",
    "Cotton": "Хлопковый",
    "Wool": "Шерстяной",
    "Linen": "Льняной",
    "Silk": "Шёлковый",
    "Velvet": "Бархатный",
    "Polished": "Полированный",
    "Painted": "Расписной",
    "Carved": "Резной",
    "Woven": "Плетёный",
    "Embroidered": "Вышитый",
    "Printed": "Печатный",
    "Stained": "Тонированный",
    "Rustic": "Деревенский",
    "Industrial": "Индустриальный",
    "Steel": "Стальной",
    "Brass": "Латунный",
    "Copper": "Медный",
    "Bronze": "Бронзовый",
    "Iron": "Железный",
    "Wrought": "Кованый",
    "Cast": "Литой",
    "Forged": "Кованый",
    "Recycled": "Переработанный",
    "Natural": "Натуральный",
    "Organic": "Органический",
    "Tropical": "Тропический",
    "Wild": "Дикий",
    "Dried": "Сушёный",
    "Fresh": "Свежий",
    "Frozen": "Замороженный",
    "Canned": "Консервированный",
    "Packaged": "Упакованный",
    "Loose": "Россыпью",
    "Bulk": "Оптом",
    "Sample": "Образец",
    "Trial": "Пробный",
    "Demo": "Демо",
    "Test": "Тестовый",
    "Display": "Витринный",
    "Exhibition": "Выставочный",
    "Museum": "Музейный",
    "Collectible": "Коллекционный",
    "Rare": "Редкий",
    "Limited": "Лимитированный",
    "Exclusive": "Эксклюзивный",
    "Special": "Специальный",
    "Edition": "Издание",
    "Version": "Версия",
    "Model": "Модель",
    "Type": "Тип",
    "Style": "Стиль",
    "Design": "Дизайн",
    "Pattern": "Узор",
    "Color": "Цвет",
    "Colour": "Цвет",
    "Size": "Размер",
    "Shape": "Форма",
    "Material": "Материал",
    "Finish": "Отделка",
    "Texture": "Текстура",
    "Surface": "Поверхность",
    "Edge": "Кромка",
    "Handle": "Ручка",
    "Leg": "Ножка",
    "Base": "Основание",
    "Top": "Столешница",
    "Panel": "Панель",
    "Board": "Доска",
    "Slab": "Плита",
    "Tile": "Плитка",
    "Block": "Блок",
    "Piece": "Часть",
    "Part": "Деталь",
    "Section": "Секция",
    "Unit": "Блок",
    "Set": "Набор",
    "Pair": "Пара",
    "Group": "Группа",
    "Collection": "Коллекция",
    "Series": "Серия",
    "Line": "Линейка",
    "Range": "Ассортимент",
    "Brand": "Бренд",
    "Make": "Марка",
    "Model": "Модель",
    "Number": "Номер",
    "Code": "Код",
    "Name": "Название",
    "Title": "Название",
    "Label": "Этикетка",
    "Tag": "Бирка",
    "Mark": "Марка",
    "Sign": "Знак",
    "Symbol": "Символ",
    "Icon": "Иконка",
    "Image": "Изображение",
    "Picture": "Картина",
    "Photo": "Фото",
    "Portrait": "Портрет",
    "Landscape": "Пейзаж",
    "Still Life": "Натюрморт",
    "Abstract": "Абстрактный",
    "Realistic": "Реалистичный",
    "Minimalist": "Минималистичный",
    "Ornate": "Украшенный",
    "Plain": "Простой",
    "Simple": "Простой",
    "Fancy": "Нарядный",
    "Elegant": "Элегантный",
    "Cute": "Милый",
    "Pretty": "Красивый",
    "Beautiful": "Красивый",
    "Ugly": "Некрасивый",
    "Strange": "Странный",
    "Weird": "Странный",
    "Odd": "Необычный",
    "Unique": "Уникальный",
    "Rare": "Редкий",
    "Common": "Обычный",
    "Standard": "Стандартный",
    "Typical": "Типичный",
    "Normal": "Обычный",
    "Regular": "Обычный",
    "Special": "Специальный",
    "Extra": "Дополнительный",
    "Bonus": "Бонусный",
    "Free": "Бесплатный",
    "Gift": "Подарочный",
    "Sample": "Образец",
    "Trial": "Пробный",
    "Test": "Тестовый",
    "Demo": "Демо",
    "Display": "Витринный",
    "Exhibition": "Выставочный",
    "Museum": "Музейный",
    "Collectible": "Коллекционный",
    "Rare": "Редкий",
    "Limited": "Лимитированный",
    "Exclusive": "Эксклюзивный",
}
WORDS.update(WORDS_FIX_TRANSLIT)

import re

# Транслитерация латиницы -> кириллица (для оставшихся слов после глоссария)
_LAT_EXTRA = {
    "a": "а", "b": "б", "c": "к", "d": "д", "e": "е", "f": "ф", "g": "г", "h": "х",
    "i": "и", "j": "й", "k": "к", "l": "л", "m": "м", "n": "н", "o": "о", "p": "п",
    "q": "ку", "r": "р", "s": "с", "t": "т", "u": "у", "v": "в", "w": "в", "x": "кс",
    "y": "й", "z": "з",
}


def _transliterate_word(word):
    """Транслитерация одного латинского слова в кириллицу."""
    if not word:
        return word
    result = []
    i = 0
    w = word.lower()
    while i < len(w):
        # Диграфы (англ. -> рус. по звучанию)
        if i < len(w) - 1:
            two = w[i : i + 2]
            if two == "ch": result.append("ч"); i += 2; continue
            if two == "sh": result.append("ш"); i += 2; continue
            if two == "zh": result.append("ж"); i += 2; continue
            if two == "kh": result.append("х"); i += 2; continue
            if two == "ts": result.append("ц"); i += 2; continue
            if two == "ya": result.append("я"); i += 2; continue
            if two == "yu": result.append("ю"); i += 2; continue
            if two == "yo": result.append("ё"); i += 2; continue
            if two == "ck": result.append("к"); i += 2; continue
            if two == "ee": result.append("и"); i += 2; continue
            if two == "oo": result.append("у"); i += 2; continue
        c = w[i]
        result.append(_LAT_EXTRA.get(c, c))
        i += 1
    s = "".join(result)
    if word and word[0].isupper():
        s = s.capitalize() if len(s) else s
    return s


def translate_item_name(en_value):
    """Превращает английское название в естественное русское (по глоссарию + транслитерация)."""
    if not en_value or not isinstance(en_value, str):
        return en_value
    s = en_value.strip()
    # Сначала полные фразы (длинные в приоритете)
    for phrase in sorted(PHRASES.keys(), key=len, reverse=True):
        if phrase in s:
            s = s.replace(phrase, PHRASES[phrase])
    # Потом отдельные слова (длинные в приоритете)
    for word in sorted(WORDS.keys(), key=len, reverse=True):
        pattern = r"\b" + re.escape(word) + r"\b"
        if re.search(pattern, s, re.IGNORECASE):
            s = re.sub(pattern, WORDS[word], s, flags=re.IGNORECASE)
    # Оставшиеся латинские слова — транслитерация (чтобы перевести все ItemName)
    def replace_latin(m):
        return _transliterate_word(m.group(0))
    s = re.sub(r"[A-Za-z]+", replace_latin, s)
    return s.strip() if s.strip() else en_value


def _has_latin(text):
    """Есть ли в тексте латинские буквы (непереведённый английский)."""
    return bool(re.search(r"[a-zA-Z]", text))


def build_item_name_dict(english_keys):
    """Строит словарь ItemName -> русский из english_keys (все ключи: глоссарий + транслитерация)."""
    result = {}
    for key, value in english_keys.items():
        if key.startswith("ItemName/") and value:
            ru = translate_item_name(value)
            if ru and not _has_latin(ru):
                result[key] = ru
    return result
